# -*- coding: utf-8 -*-
"""seed_identification__multi_cls__cnn_tl_exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_YUzCoXOvIjW2tOFRvhJkhxPz_6zsJo

# **Seed Identification**: Computer Vision - Supervised Multi-Class CNN with Transfer Learning
---

## **Value Proposition**

In order to automate manual plant/seedling sorting a CNN was developed that classifies **12 plant species at 89.3% test accuracy**, targeting recovery of weed-related crop losses estimated at **$32B annually** with potential herbicide reduction of **60–90%**.

---

## **Executive Summary**

### Business Opportunities

* **Opportunity A:** Weeds cause an estimated **34% yield loss** (approximately **$32B annually**). Automated detection provides the best known opportunity to recover a significant share of that loss.

* **Solution A:** The current Custom CNN operates as an **89.3% accurate detection layer**, providing a credible base for targeted intervention and a meaningful recovery ceiling against weed-driven losses. Further model development and broader species coverage would raise that ceiling.

* **Opportunity B:** Precision weeding is projected to reach **$10.65B by 2034** (approximately **17% CAGR**).

* **Solution B:** Vision-based systems like this are shown in existing field studies to reduce herbicide use (the current implementation process) by **60–90%**.

* **Opportunity C:** Multiple deployment paths exist for this model across a growing precision agriculture market.

* **Solution C** (Options): Embedded vision module retrofitted onto existing sprayer booms (**John Deere See & Spray**). Onboard classification for autonomous robotic platforms (**Solinftec Solix**). Aerial detection via drone-mounted inference (**emerging sector, no dominant player**). Edge-deployed mobile app for manual scouting support (**agronomist field tools**).

### Outcomes

* **Model Performance**

  * **Custom CNN** achieved **89.3% test accuracy** and is the strongest current model.
  * **MobileNetV2 + TTA** achieved **81.1% test accuracy** and remains a useful secondary architecture.
  * The current results support continued development of both models: the Custom CNN as the primary near-term performer and MobileNetV2 as a secondary architecture for broader scaling, future model blending, and expanded species coverage.

* **Architecture**

  * The lighter Custom CNN outperforming MobileNetV2 is viable as:

    * a retrofit on components in purpose-built existing equipment or platforms

    * a component that can develop in purpose-built platforms

  * Retaining and continuing to develop both models enables:

     * ensemble opportunities

     * scaling across additional species

     * architectural flexibility across different deployment targets

* **Economic Impact**

  * Recovering even a fraction of the **$32B** annual weed-related yield loss through automated detection represents significant value, while reducing herbicide use by **60–90%** directly lowers input costs.

* **Strategy Recommendation**

  * **Enterprise:** Develop and retain both models within the product roadmap, using the Custom CNN as the current performance leader while continuing MobileNetV2 as a secondary architecture for scaling across additional species, deployment environments, and future ensemble options.

  * **SMB:** Develop and retain both models as well, using the Custom CNN for the strongest near-term accuracy while keeping MobileNetV2 in the stack to support lower-footprint deployment experiments, broader species coverage, and future model blending.

---

## **Problem Space**

### Overview

* Current seedling identification is slow, inconsistent, and does not scale. The most common herbicide use techniques are inefficient.

* Misidentifying weeds as crops (or vice versa) leads directly to yield loss or wasted resources.

* With the precision weeding market projected to reach **$10.65B by 2034** (~**17% CAGR**), demand for automated visual classification is clear.

### Data Description

* **4,750** labeled images of **12** plant seedling species, preprocessed to **128×128** resolution.

* Sourced from `images_plant.npy` and `labels.csv`.

### Process

* Two deep learning approaches were compared:

  * **Part A — Custom CNN:** Three convolutional blocks (**32→64→128**), batch normalization, dropout, real-time augmentation, learning rate scheduling.
  
  * **Part B — MobileNetV2 Transfer Learning:** ImageNet-pretrained, fine-tuned on the last 30 layers, cosine-decay LR, test-time augmentation.

* Both used an **80 / 10 / 10** stratified split.

### Results
>| Model | Test Accuracy | Weighted F1 | Position |
>|---|---:|---:|---|
>| **Model 1: Custom CNN ✅** | **89.3%** | **0.90** | Best current model |
>| Model 2: MobileNetV2 + TTA | **81.1%** | **0.81** | Secondary architecture |

# **Execute Code**
*   Installing Colab Dependecies may require a Runtime restart. You will be notified if a restart is required
*   Data cited in markdown cells may differ sligntly from outputs, as training data and test data are randomized

### **Runtime Configuration**

> **Hardware Accelerator:** **L4 GPU** (or T4 GPU) and **High-RAM**
>
> Please ensure the Colab runtime is set to this configuration before executing any code cells to avoid memory errors or protracted training times.

### Library Import

**Process:** Core libraries for data loading, visualization, augmentation, CNN training, transfer learning, and evaluation are initialized for the full workflow.

**Outcome:** The notebook environment is ready to train and compare the custom CNN and MobileNetV2 pipelines.
"""

# ------------------------------
# LIBRARY IMPORT
# ------------------------------
# Imports libraries for image classification: data handling, visualization, deep learning, and metrics.

import numpy as np  # for numerical arrays, image tensor operations, and vectorized computations
import pandas as pd  # for reading and handling the labels table
import matplotlib.pyplot as plt  # for plotting distributions, curves, and sample images
import seaborn as sns  # for statistical visualizations such as countplots and heatmaps
import cv2  # for image-processing utilities used later in the notebook
import tensorflow as tf  # for deep learning model training and TensorFlow backend operations
from tensorflow.keras.models import Sequential  # for building the custom CNN model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization  # for CNN feature extraction, regularization, and classification layers
from tensorflow.keras.optimizers import Adam  # for Adam-based neural network optimization
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint  # for adaptive learning-rate control, early stopping, and checkpoint saving
from tensorflow.keras.preprocessing.image import ImageDataGenerator  # for real-time image augmentation during training
from sklearn.model_selection import train_test_split  # for stratified train/validation/test splitting
from sklearn.preprocessing import LabelBinarizer  # for one-hot encoding class labels
from sklearn.metrics import confusion_matrix, classification_report  # for post-training classification evaluation

"""### Data Loading

**Process:** The managed dataset package is resolved through the notebook-specific helper and loaded from `images_plant.npy` and `labels.csv`.

**Outcome:** The notebook loads 4,750 RGB seedling images with matching labels, with image shape `(4750, 128, 128, 3)` and label shape `(4750,)`.
"""

# ------------------------------
# DATA LOADING
# ------------------------------
# Downloads the standardized dataset automatically and loads images + labels.

import importlib.util  # for loading the shared data access helper dynamically
import shutil  # for clearing stale notebook-specific cached dataset folders
import sys  # for detecting whether the notebook is running in Colab
import urllib.request  # for downloading the shared helper file from GitHub
from pathlib import Path  # for cross-platform file path handling
import numpy as np  # for loading the image tensor file in this self-contained cell
import pandas as pd  # for loading the labels table in this self-contained cell

HELPER_URL = "https://raw.githubusercontent.com/EvagAIML/000-website-notebooks/main/notebooks/_shared/data_access.py"

SLUG = "seed-identification__multi-cls__cnn-tl-exp"
EXTRACT_TO = "seed-identification__multi-cls__cnn-tl-exp__dataset__v2"
ZIP_NAME = "seed-identification__multi-cls__cnn-tl-exp__dataset__v2.zip"

helper_path = Path("/content/data_access.py") if "google.colab" in sys.modules else Path("./data_access.py")
cache_root = Path("/content/data_cache") if "google.colab" in sys.modules else Path("./data_cache")
session_flag = Path("/content/.seed_cache_refreshed") if "google.colab" in sys.modules else Path(".seed_cache_refreshed")

# Clear stale notebook-specific artifacts once per fresh session
if not session_flag.exists():
    helper_path.unlink(missing_ok=True)
    shutil.rmtree(cache_root / EXTRACT_TO, ignore_errors=True)
    (cache_root / ZIP_NAME).unlink(missing_ok=True)
    session_flag.touch()

urllib.request.urlretrieve(HELPER_URL, helper_path)

spec = importlib.util.spec_from_file_location("data_access", helper_path)
data_access = importlib.util.module_from_spec(spec)
spec.loader.exec_module(data_access)

ensure_dataset = data_access.ensure_dataset

DATA_DIR = ensure_dataset(SLUG)
RAW_DIR = DATA_DIR / "raw"

images = np.load(RAW_DIR / "images_plant.npy")

labels_df = pd.read_csv(RAW_DIR / "labels.csv")
labels = labels_df["Label"]

print(f"Images shape: {images.shape}")
print(f"Labels shape: {labels.shape}")

"""### Exploratory Data Analysis (EDA)

**Process:** Species counts are visualized to assess class balance before splitting and training.

**Analysis:** Loose Silky-bent is visibly overrepresented, so stratified splitting is important to reduce majority-class bias.

**Outcome:** Class balance is understood before preprocessing and model training.
"""

# ------------------------------
# EXPLORATORY DATA ANALYSIS (EDA)
# ------------------------------
# Plots species class frequencies to assess balance before training.

plt.figure(figsize=(12, 6))
sns.countplot(x=labels)
plt.xticks(rotation=45, ha='right')
plt.title('Distribution of Plant Seedling Species')
plt.show()

"""### **Data Preprocessing: Normalization and Label Encoding**

**Process:** Pixel values are scaled to `[0,1]` and labels are one-hot encoded for 12-class softmax training.

**Outcome:** Inputs are normalized to a max value of `1.0`, and encoded labels have shape `(4750, 12)`.
"""

# ------------------------------
# DATA PREPROCESSING: NORMALIZATION AND LABEL ENCODING
# ------------------------------
# Scales pixels to 0-1 and one-hot encodes species labels for multi-class classification.
# sklearn.preprocessing.LabelBinarizer handles one-hot encoding.

images_norm = images.astype('float32') / 255.0

# Encode labels
lb = LabelBinarizer()
labels_encoded = lb.fit_transform(labels)

print(f'Normalized images max value: {images_norm.max()}')
print(f'Encoded labels shape: {labels_encoded.shape}')

"""### Train / Validation / Test Split

**Process:** The dataset is split with stratification into training, validation, and test sets.

**Outcome:** The saved run uses an `80 / 10 / 10` split with shapes `3800 / 475 / 475`, correcting the earlier 70/30 description.
"""

# ------------------------------
# TRAIN / VALIDATION / TEST SPLIT
# ------------------------------
# Splits data 80/10/10 with stratification to preserve class proportions.

# First split: 80% train, 20% holdout.
X_train, X_temp, y_train, y_temp = train_test_split(images_norm, labels_encoded, test_size=0.2, random_state=42, stratify=labels)

# Second, split Temp into 50% Val and 50% Test (which is 10% and 10% of total)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=lb.inverse_transform(y_temp))

print(f'Training set shape: {X_train.shape}')
print(f'Validation set shape: {X_val.shape}')
print(f'Test set shape: {X_test.shape}')

"""### Data Augmentation

**Process:** Real-time augmentation applies rotations, zooms, shifts, and flips to training images.

**Analysis:** This increases variation without collecting new data and helps the model generalize beyond the fixed training set.

**Outcome:** The training pipeline is configured to expose the CNN to more diverse seedling views.
"""

# ------------------------------
# DATA AUGMENTATION
# ------------------------------
# Configures real-time augmentation (rotation, zoom, shift, flip) to improve generalization.
# keras.preprocessing.image.ImageDataGenerator applies transforms during training.

datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

datagen.fit(X_train)

# Visualize augmentation on one image
plt.figure(figsize=(10, 2))
for i in range(5):
    img = X_train[0].reshape((1, 128, 128, 3))
    batch = datagen.flow(img, batch_size=1)
    plt.subplot(1, 5, i+1)
    plt.imshow(batch[0][0])
    plt.axis('off')
plt.suptitle('Augmentation Examples')
plt.show()

"""### CNN Model Architecture

**Process:** A custom 3-block CNN with batch normalization, dropout, and a 12-class softmax head is constructed for direct species classification.

**Outcome:** A purpose-built image classifier is ready for training on the normalized seedling dataset.
"""

# ------------------------------
# CNN MODEL ARCHITECTURE
# ------------------------------
# Builds a three-block CNN (32→64→128 filters) with batch normalization and dropout.

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Conv2D(128, (3, 3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D((2, 2)),

    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(12, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

"""### Model Training: CUSTOM CNN

**Process:** The custom CNN is trained with augmented batches, validation monitoring, learning-rate reduction, and best-model checkpointing.

**Analysis:** Validation performance improves materially after the learning rate is reduced, and the best checkpoint is reloaded before evaluation.

**Outcome:** The notebook produces a saved best custom-CNN model for downstream testing.
"""

# ------------------------------
# MODEL TRAINING
# ------------------------------
# Trains the CNN with learning rate reduction on plateau and best-model checkpointing.

# Halves learning rate after 3 epochs of no improvement.
reduce_lr = ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, min_lr=0.00001, verbose=1)
# Saves weights when validation loss hits a new minimum.
checkpoint = ModelCheckpoint('best_model.keras', monitor='val_loss', save_best_only=True, mode='min', verbose=1)

# Use datagen.flow for training
history = model.fit(datagen.flow(X_train, y_train, batch_size=64),
                    epochs=25,  # Increased epochs slightly given augmentation
                    validation_data=(X_val, y_val),
                    callbacks=[reduce_lr, checkpoint])

# ------------------------------
# LOAD BEST MODEL
# ------------------------------
# Restores the best checkpoint; falls back to the current model if unavailable.

try:
    model = tf.keras.models.load_model('best_model.keras')
    print("Loaded best model from checkpoint.")
except:
    print("Could not load checkpoint, using current model state.")

"""### Model A Evaluation: Custom CNN

**Process:** The custom CNN is evaluated using learning curves, a confusion matrix, and a per-class classification report.

**Analysis:** The saved run reaches about `89.3%` test accuracy, with strong performance on Fat Hen (`0.99` F1) and the main weakness on Shepherds Purse (`0.55` F1), reflecting confusion among visually similar species.

**Outcome:** The custom CNN establishes a strong baseline for comparison against transfer learning.
"""

# ------------------------------
# MODEL A EVALUATION: CUSTOM CNN
# ------------------------------
# Evaluates the CNN with training curves, confusion matrix, and per-class classification report.

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.legend()
plt.title('Accuracy')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.legend()
plt.title('Loss')
plt.show()

# Confusion Matrix and Classification Report
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_true_classes, y_pred_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=lb.classes_, yticklabels=lb.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Per-species precision, recall, and F1.
print(classification_report(y_true_classes, y_pred_classes, target_names=lb.classes_))

"""### Prediction Visualization

**Process:** Random test images are displayed with their true and predicted labels for qualitative review.

**Outcome:** The notebook provides a quick visual check of where the custom CNN is succeeding and failing.
"""

# ------------------------------
# PREDICTION VISUALIZATION
# ------------------------------
# Displays five random test images with true vs. predicted labels as a sanity check.

plt.figure(figsize=(15, 5))
for i in range(5):
    idx = np.random.randint(0, len(X_test))
    img = X_test[idx]
    true_label = lb.classes_[y_true_classes[idx]]
    pred_label = lb.classes_[y_pred_classes[idx]]

    plt.subplot(1, 5, i+1)
    plt.imshow(img)
    plt.title(f'True: {true_label}\nPred: {pred_label}')
    plt.axis('off')
plt.show()

"""### Model Insights: Custom CNN

**Process:** The custom-CNN results are summarized and the main improvement opportunities are identified.

**Analysis:** Remaining errors are concentrated in visually similar or underrepresented classes, which supports trying stronger augmentation, class weighting, or alternative architectures.

**Outcome:** The notebook defines the key issues to address in the transfer-learning comparison.
"""

# ------------------------------
# MODEL A INSIGHTS: CUSTOM CNN
# ------------------------------
# Summarizes findings and identifies improvement opportunities for the next iteration.

print("1. The model performs well overall but struggles with species that have similar leaf structures.")
print("2. Data augmentation (rotation, zooming) could further improve generalization.")
print("3. Class weighting could address the imbalance observed in the EDA phase.")

"""### Transfer Learning Model B: MobileNetV2

**Process:** MobileNetV2 is initialized with ImageNet weights, fine-tuned on the last 30 layers, trained with cosine-decay learning rate, and evaluated with test-time augmentation.

**Analysis:** Despite pretrained features and TTA, the saved run underperforms the custom CNN on this dataset, suggesting the smaller purpose-built model fits this problem better.

**Outcome:** MobileNetV2 + TTA reaches about `81.1%` test accuracy and remains the weaker of the two approaches in the current run.
"""

# ------------------------------
# TRANSFER LEARNING MODEL B: MOBILENETV2
# ------------------------------
# Builds a MobileNetV2 transfer learning model with a frozen pretrained base and custom head.
# keras.applications.MobileNetV2 provides the pretrained feature extractor.

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Load MobileNetV2 without top layers, input size 128x128
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(128, 128, 3))

# Freeze the base model initially
base_model.trainable = False

# Add custom head
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(12, activation='softmax')(x)

model_b = Model(inputs=base_model.input, outputs=predictions)

model_b.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_b.summary()

"""### Fine-Tuning Setup

**Process:** The last 30 MobileNetV2 layers are unfrozen and the model is recompiled with a low cosine-decay learning rate.

**Analysis:** This shifts the transfer-learning model from frozen feature extraction to controlled domain adaptation while limiting the risk of overwriting pretrained features too aggressively.

**Outcome:** MobileNetV2 is recompiled and ready for fine-tuning on the seedling dataset.
"""

# ------------------------------
# FINE-TUNING SETUP
# ------------------------------
# Unfreezes the last 30 MobileNetV2 layers with cosine-decay learning rate to avoid catastrophic forgetting.

base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

# Implement Cosine Decay Learning Rate
initial_learning_rate = 0.0001
decay_steps = 1000
cosine_decay = tf.keras.optimizers.schedules.CosineDecay(initial_learning_rate, decay_steps)

# Recompile with low learning rate
model_b.compile(optimizer=Adam(learning_rate=cosine_decay), loss='categorical_crossentropy', metrics=['accuracy'])
print("Model B re-compiled for fine-tuning.")

"""### Transfer Learning Training

**Process:** The fine-tuned MobileNetV2 model is trained for 20 epochs using augmented batches, validation monitoring, and checkpointing on validation loss.

**Outcome:** A best-performing MobileNetV2 checkpoint is saved for downstream inference and comparison.
"""

# ------------------------------
# TRANSFER LEARNING TRAINING
# ------------------------------
# Trains the fine-tuned MobileNetV2 for 20 epochs with checkpointing.

checkpoint_b = ModelCheckpoint('best_model_b.keras', monitor='val_loss', save_best_only=True, mode='min', verbose=1)

# Use the same datagen as before
history_b = model_b.fit(datagen.flow(X_train, y_train, batch_size=64),
                        epochs=20,  # Fine-tune for 20 epochs
                        validation_data=(X_val, y_val),
                        callbacks=[checkpoint_b])

"""### Test-Time Augmentation

**Process:** Multiple augmented versions of each test image are scored and averaged to produce final MobileNetV2 predictions.

**Analysis:** This reduces single-view prediction variance and gives the transfer-learning model its strongest evaluation setting.

**Outcome:** Final MobileNetV2 test predictions are generated using test-time augmentation.
"""

# ------------------------------
# TEST-TIME AUGMENTATION
# ------------------------------
# Averages predictions over multiple augmented copies of each test image to reduce variance.

# Generates n augmented versions per image and averages their softmax outputs.
def predict_tta(model, images, n_aug=5):
    predictions = []
    for img in images:
        # Create batch of augmented versions
        img_expanded = img.reshape((1, 128, 128, 3))
        aug_images = [datagen.random_transform(img) for _ in range(n_aug)]
        aug_batch = np.array(aug_images)

        # Predict on augmented batch
        preds = model.predict(aug_batch, verbose=0)

        # Average predictions
        avg_pred = np.mean(preds, axis=0)
        predictions.append(avg_pred)
    return np.array(predictions)

print("Running TTA on Model B...")
# Load best model B
try:
    model_b = tf.keras.models.load_model('best_model_b.keras')
except:
    pass

y_pred_b = predict_tta(model_b, X_test, n_aug=5)
y_pred_classes_b = np.argmax(y_pred_b, axis=1)
print("TTA Predictions Complete.")

"""### Transfer Learning Evaluation

**Process:** MobileNetV2 is evaluated using training curves and a classification report on the test set.

**Analysis:** This shows whether fine-tuning and test-time augmentation improved generalization enough to make transfer learning competitive with the custom CNN.

**Outcome:** Model B’s final test performance is quantified and ready for direct comparison.
"""

# ------------------------------
# TRANSFER LEARNING EVALUATION
# ------------------------------
# Evaluates Model B with training curves and classification report.

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_b.history['accuracy'], label='Train Acc')
plt.plot(history_b.history['val_accuracy'], label='Val Acc')
plt.title('Model B Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_b.history['loss'], label='Train Loss')
plt.plot(history_b.history['val_loss'], label='Val Loss')
plt.title('Model B Loss')
plt.legend()
plt.show()

print(classification_report(y_true_classes, y_pred_classes_b, target_names=lb.classes_))

"""### Model Comparison (Model A vs Model B)

**Process:** Test accuracy from the custom CNN and MobileNetV2 + TTA is calculated and displayed side by side.

**Analysis:** The saved comparison confirms that the custom CNN outperforms the transfer-learning model on this dataset, achieving `0.892632` accuracy versus `0.810526`. This reinforces the earlier pattern in the notebook: the purpose-built CNN generalizes better than MobileNetV2 + TTA for this 12-class, 4,750-image seedling classification task.

**Outcome:** The custom CNN remains the preferred model for the current deployment path, while MobileNetV2 is retained as a secondary architecture for future comparison or ensemble exploration.
"""

# ------------------------------
# MODEL COMPARISON (Model A vs Model B)
# ------------------------------
# Compares test accuracy between the custom CNN and MobileNetV2 + TTA.
# sklearn.metrics.accuracy_score computes overall accuracy for each model.

from sklearn.metrics import accuracy_score

acc_a = accuracy_score(y_true_classes, y_pred_classes)
acc_b = accuracy_score(y_true_classes, y_pred_classes_b)

results = pd.DataFrame({
    'Model': ['Custom CNN (Part A)', 'MobileNetV2 + TTA (Part B)'],
    'Test Accuracy': [acc_a, acc_b]
})

print(results)

plt.figure(figsize=(6, 4))
sns.barplot(x='Model', y='Test Accuracy', data=results)
plt.title('Model Performance Comparison')
plt.ylim(0, 1.0)
plt.show()

"""### **Expanded Executive Summary**

**TLDR**

The **Custom CNN** is the leading near-term commercial model, delivering **89.3%** test accuracy versus **81.1%** for **MobileNetV2 + TTA**. That makes it the strongest current deployment path for addressing weed-related crop-loss exposure estimated at **\$32B annually**, with meaningful upside through better treatment precision, lower herbicide waste, and improved field efficiency. Retaining both models preserves strategic optionality for scaling across additional species, deployment environments, and future multi-model offerings.

**Full Summary**

**Objective:** This project established a computer vision pipeline for automated plant seedling classification across **12 species**, with the goal of improving precision weeding, reducing unnecessary herbicide application, and supporting more scalable crop-management workflows. The commercial relevance comes from improving treatment accuracy where field decisions are made, which directly affects crop protection, chemical usage, and labor efficiency.

**Iterative Development:** Two architectures were developed and compared on the same managed dataset of **4,750 labeled seedling images**: a purpose-built **Custom CNN** trained from scratch and a **MobileNetV2** transfer-learning pipeline with fine-tuning and test-time augmentation. Both used the same preprocessing flow, normalized inputs, one-hot encoded labels, and an **80 / 10 / 10** stratified split, so the final comparison reflects architecture quality rather than inconsistent data handling.

**Performance Analysis:** In the saved run, the **Custom CNN** achieved **0.892632** test accuracy, outperforming **MobileNetV2 + TTA** at **0.810526**. This confirms that the purpose-built CNN is the better fit for the current dataset and the strongest near-term deployment candidate. The broader evaluation pattern suggests that remaining errors are concentrated in visually similar species, which is a targeted improvement problem rather than a sign of weak overall model utility. From a business perspective, this is important because it means the current model is already strong enough to support practical deployment experiments while still leaving meaningful room for performance expansion.

**Economic Impact:** The value of this system comes from improving identification quality at the point where spraying, sorting, or scouting decisions are made. In practical terms, that means more targeted herbicide use, lower input waste, reduced manual scouting burden, and stronger yield protection. The notebook’s business framing ties this to weed-related crop losses estimated at **\$32B annually**. If current model performance translated linearly into usable detection capability, the Custom CNN’s **89.3%** result suggests a theoretical ceiling of approximately **\$28.6B** in loss exposure that could eventually be addressed. A more realistic commercialization view is to assume partial capture of that opportunity: **5% capture implies ~\$1.6B**, **10% implies ~\$3.2B**, and **20% implies ~\$6.4B** in potential value. These are directional scenario estimates rather than forecasted outcomes, but they show that even modest deployment success could be economically meaningful.

**Deployment Readiness:** The **Custom CNN** should be treated as the primary deployment track because it delivers the strongest current performance with a simpler architecture, making it the best fit for near-term precision-weeding workflows. Likely implementation paths include embedded vision modules on sprayer booms, onboard classification for autonomous field platforms, drone-based detection, and mobile field-support tools. However, both models should continue to be developed. Retaining **MobileNetV2** strengthens the roadmap by preserving flexibility across different compute environments, supporting future ensemble options, and improving the project’s ability to scale across additional plant species and more operationally diverse image conditions.

**Next Steps:** The next phase should focus on improving performance on visually similar classes, validating robustness under more variable field conditions, and expanding the dataset to cover additional species and more realistic deployment imagery. The **Custom CNN** should remain the lead model for near-term deployment and commercial pilots, while **MobileNetV2** should remain active as a secondary architecture for scaling experiments, species expansion, and future multi-model development.
"""