# -*- coding: utf-8 -*-
"""turbine_failure_pred__bin_cls__dnn_exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grqZW8O-dK9Dee0PSKh0d8QQv3BbsavO

# **Turbine Failure Prediction**: Supervised Binary Classification DNN
---

## **Value Proposition**

In order to prevent unexpected wind turbine breakdowns, a predictive maintenance DNN was developed that identifies **nearly 87% of failures on the held-out test set**, potentially avoiding **\$2.5M–\$4M** per replacement and up to **\$17,000 per day** in downtime per turbine.  Two models both appear as strong deployment contenders, but Model 5 (a DNN with dropout) has the strongest overall data profile and the clearest long-term deployment potential case, making it the better lead model for further development.

---

## **Executive Summary**

### Business Opportunities

* **Opportunity A:** Replacing a wind turbine typically costs **\$2.5M–\$4M**, and unplanned failures can also trigger major lost-generation and emergency-maintenance costs. Preventing unexpected breakdowns is therefore one of the highest-value use cases in predictive maintenance.

* **Solution A:** The current lead model, **Model 5**, identifies **86.9%** of failures on the held-out test set, providing a credible early-warning layer for inspection prioritization and intervention planning.

* **Opportunity B:** Wind turbine downtime losses can range from **\$3,000 to \$17,000 per day per turbine**, making even modest gains in early detection economically meaningful.

* **Solution B:** A model that detects failures earlier can improve fleet availability, reduce emergency-maintenance exposure, and shift maintenance from reactive replacement toward planned intervention.

* **Opportunity C:** Multiple integration paths exist for this model across the renewable energy and predictive maintenance markets.

* **Solution C** (Options): Operational integration into existing predictive maintenance systems. API integration into fleet-management dashboards for dispatchers. Edge deployment on turbine monitoring hardware for real-time alerting.

### Outcomes

* **Model Performance**

  * On initial comparison numbers, **Model 6** can appear stronger because it posts the highest saved validation recall and F1.
  * However, **Model 5** has the strongest overall data profile: it combines strong validation performance with the clearest held-out test confirmation, where it achieves **99.16% accuracy**, **86.88% recall**, **98.0% precision**, and **0.921 F1**.
  * Successive training runs can shift the exact gap between top models, so model selection should be based on the strongest overall evidence rather than one metric in one run. On the current saved run, that still supports **Model 5** as the lead deployment model and **Model 6** as the strongest challenger.

* **Architecture**

  * The notebook shows that architecture depth, dropout, class-imbalance handling, and optimizer choice all materially affect the precision-recall tradeoff.
  * **Model 5** currently provides the best deployment balance, while **Model 6** preserves upside if future development can improve recall leadership without materially worsening false alarms.

* **Economic Impact**

  * Detecting failures earlier can reduce unscheduled downtime, avoid high-cost replacements, and improve maintenance-planning efficiency.
  * In commercial terms, the value is not just predictive accuracy—it is avoiding the most expensive failure events while minimizing unnecessary interventions.

* **Strategy Recommendation**

  * **Enterprise:** Continue developing both **Model 5** and **Model 6**. **Model 5** should lead the near-term deployment path because it has the strongest overall data profile and explicit held-out test confirmation. **Model 6** should remain in active development because its stronger initial recall suggests upside if future tuning can improve failure capture without a disproportionate false-alarm penalty.

  * **SMB:** Prioritize **Model 5** as the implementation model because it provides the clearest current balance of failure detection and false-alarm control, while treating **Model 6** as a secondary R&D path rather than a parallel deployment model.

---

## **Problem Space**

### Overview

* Wind turbine component failure patterns are predictable using continuous sensor information, but manual analysis does not scale.

* Missing actual failures (**False Negatives**) can lead directly to catastrophic replacement and downtime costs.

* Misidentifying healthy turbines as failing (**False Positives**) can lead to unnecessary inspection and intervention expense.

### Data Description

* **25,000** observations total: **20,000** training rows and **5,000** test rows

* Approximately **40** anonymized numeric sensor features plus one target column

* Data files: `train.csv` and `test.csv`

* Target variable indicates failure status, where `1` represents a failure needing repair or replacement and `0` represents no failure.

* The data is strongly imbalanced, with failures representing approximately **5.55%** of the training set.

### Process

* Data preparation included train/validation splitting, median imputation of missing values, and class-imbalance handling.

* Multiple DNN architectures were built and compared to optimize the precision-recall tradeoff, with particular emphasis on catching true failures while controlling false alarms.

* Because neural-network training is stochastic, successive runs can shift the exact ranking between top models. On the current saved evidence, **Model 6** looks strongest on initial validation recall/F1, while **Model 5** has the strongest overall profile and is the only model explicitly carried through held-out test evaluation.

### Results
>| Model | Key Signal | Current Role |
>|---|---|---|
>| **Model 5: Deeper + Dropout + Adam ✅** | Held-out test: **99.16% accuracy / 86.88% recall / 98.0% precision / 0.921 F1** | Lead deployment model |
>| Model 6: Deeper + Class Weights (SGD) | Best saved validation recall/F1 among challengers: **87.84% recall / 0.922 F1** | Recall-oriented challenger |

# **Code Execution**

### **Runtime Configuration**

> **Hardware Accelerator:** **T4 GPU** and **High-RAM**
>
> Please ensure the Colab runtime is set to this configuration before executing any code cells to avoid memory errors or protracted training times.

### Library Import and Configuration

**Process:** Core libraries for tabular analysis, visualization, preprocessing, evaluation, and deep neural network modeling are initialized for the full workflow.

**Outcome:** The notebook environment is ready to load turbine sensor data, prepare features, and compare multiple binary-classification DNN architectures.
"""

# ------------------------------
# LIBRARY IMPORT AND CONFIGURATION
# ------------------------------
# Imports libraries for data handling, visualization, preprocessing, metrics, and neural networks.

import pandas as pd  # for tabular data loading, manipulation, and DataFrame operations
import numpy as np  # for numerical arrays, vectorized math, and class-weight calculations

# Visualization
import matplotlib.pyplot as plt  # for charts, loss curves, and distribution plots
import seaborn as sns  # for statistical visualizations such as heatmaps, histograms, and boxplots

# Preprocessing and metrics
from sklearn.model_selection import train_test_split  # for creating train and validation splits
from sklearn.impute import SimpleImputer  # for filling missing values using median imputation
from sklearn.preprocessing import StandardScaler  # for feature scaling if needed during preprocessing
from sklearn.metrics import (  # for evaluating classification performance
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    classification_report
)

# Deep learning
import tensorflow as tf  # for neural network training, optimization, and model utilities
from tensorflow.keras.models import Sequential  # for building layered neural network models
from tensorflow.keras.layers import Dense, Dropout  # for hidden layers and regularization

# Utility
import warnings  # for suppressing non-critical warnings during execution
warnings.filterwarnings("ignore")

print("All libraries imported successfully.")

"""### Data Loading

**Process:** The managed dataset package is resolved through the notebook-specific helper and loaded into training and test DataFrames from `train.csv` and `test.csv`.

**Outcome:** The saved run loads **20,000** training rows and **5,000** test rows, with **41 columns** in each dataset.
"""

# ------------------------------
# DATA LOADING
# ------------------------------
# Downloads the standardized dataset automatically and creates working copies.

import importlib.util  # for loading the shared data access helper dynamically
import shutil  # for clearing stale notebook-specific cached dataset folders
import sys  # for detecting whether the notebook is running in Colab
import urllib.request  # for downloading the shared helper file from GitHub
from pathlib import Path  # for cross-platform file path handling
import pandas as pd  # for loading the standardized CSV files into DataFrames

HELPER_URL = "https://raw.githubusercontent.com/EvagAIML/000-website-notebooks/main/notebooks/_shared/data_access.py"

SLUG = "turbine-failure-pred__bin-cls__dnn-exp"
EXTRACT_TO = "turbine-failure-pred__bin-cls__dnn-exp__dataset__v1"
ZIP_NAME = "turbine-failure-pred__bin-cls__dnn-exp__dataset__v1.zip"

helper_path = Path("/content/data_access.py") if "google.colab" in sys.modules else Path("./data_access.py")
cache_root = Path("/content/data_cache") if "google.colab" in sys.modules else Path("./data_cache")
session_flag = Path("/content/.turbine_cache_refreshed") if "google.colab" in sys.modules else Path(".turbine_cache_refreshed")

# Clear stale notebook-specific artifacts once per fresh session
if not session_flag.exists():
    helper_path.unlink(missing_ok=True)
    shutil.rmtree(cache_root / EXTRACT_TO, ignore_errors=True)
    (cache_root / ZIP_NAME).unlink(missing_ok=True)
    session_flag.touch()

urllib.request.urlretrieve(HELPER_URL, helper_path)

spec = importlib.util.spec_from_file_location("data_access", helper_path)
data_access = importlib.util.module_from_spec(spec)
spec.loader.exec_module(data_access)

ensure_dataset = data_access.ensure_dataset

DATA_DIR = ensure_dataset(SLUG)
RAW_DIR = DATA_DIR / "raw"

df = pd.read_csv(RAW_DIR / "train.csv")
df_test = pd.read_csv(RAW_DIR / "test.csv")

print("Train data loaded:", df.shape)
print("Test data loaded :", df_test.shape)

# keep copies
data = df.copy()
data_test = df_test.copy()

"""### Data Overview

**Process:** The datasets are checked for structure, data types, duplicates, missing values, and target balance before modeling.

**Analysis:** The data is highly imbalanced, with failures representing about **5.55%** of the training set, and missing values are present in **V1** and **V2**, so the notebook correctly prepares for imputation and recall-aware modeling.

**Outcome:** The notebook confirms a clean schema, no duplicate rows, manageable missing-value issues, and a minority failure class that requires careful model selection.
"""

# ------------------------------
# DATA OVERVIEW
# ------------------------------
# Examines structure, data types, duplicates, missing values, and target class balance.

print("4.1 Dataset shape")
print(f"- Training dataset: {data.shape[0]} rows × {data.shape[1]} columns")
print(f"- Test dataset    : {data_test.shape[0]} rows × {data_test.shape[1]} columns\n")

# 4.2 Sample records
print("4.2 First five rows of the training dataset")
display(data.head())
print()

print("4.3 First five rows of the test dataset")
display(data_test.head())
print()

# 4.4 Data types
print("4.4 Data types in the training dataset")
print(data.dtypes)
print()

print("4.5 Data types in the test dataset")
print(data_test.dtypes)
print()

# 4.6 Convert Target to float to ensure consistency
data["Target"] = data["Target"].astype(float)
data_test["Target"] = data_test["Target"].astype(float)
print("4.6 Target column converted to float in both training and test datasets.\n")

# 4.7 Duplicate records
train_duplicates = data.duplicated().sum()
test_duplicates = data_test.duplicated().sum()
print("4.7 Duplicate records")
print(f"- Training dataset duplicate rows: {train_duplicates}")
print(f"- Test dataset duplicate rows    : {test_duplicates}\n")

# 4.8 Missing values
print("4.8 Missing values in the training dataset")
train_missing = data.isnull().sum()
if train_missing.sum() == 0:
    print("- No missing values detected in the training dataset.\n")
else:
    display(train_missing[train_missing > 0])
    print()

print("4.9 Missing values in the test dataset")
test_missing = data_test.isnull().sum()
if test_missing.sum() == 0:
    print("- No missing values detected in the test dataset.\n")
else:
    display(test_missing[test_missing > 0])
    print()

# 4.10 Statistical summary
print("4.10 Statistical summary of numerical variables (training dataset)")
display(data.describe().T)
print()

# 4.11 Target distribution
print("4.11 Target distribution in the training dataset")
train_target_counts = data["Target"].value_counts(normalize=True)
for cls, prop in train_target_counts.items():
    print(f"- Class {int(cls)}: {prop*100:.2f}%")
print()

print("4.12 Target distribution in the test dataset")
test_target_counts = data_test["Target"].value_counts(normalize=True)
for cls, prop in test_target_counts.items():
    print(f"- Class {int(cls)}: {prop*100:.2f}%")
print("Data overview complete.\n")

"""### Exploratory Data Analysis (EDA)

**Process:** Univariate distributions, target balance, grouped feature means, and feature correlations are reviewed to understand separation and modeling risk.

**Analysis:** Several numeric features show class-level separation, while the severe class imbalance reinforces the need to judge models on recall, precision, and F1 rather than accuracy alone.

**Outcome:** The notebook establishes that the data contains signal for failure prediction but requires imbalance-aware evaluation.
"""

# ------------------------------
# EXPLORATORY DATA ANALYSIS
# ------------------------------
# Univariate distributions and bivariate analysis (feature means by target, correlation heatmap).

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------
# Helper: boxplot + histogram (fixed bins handling)
# ------------------------------------------------------------
def histogram_boxplot(df, feature, figsize=(12, 6), kde=False, bins=None):
    """
    Draws a boxplot (top) and histogram (bottom) for a numeric feature.
    """
    fig, (ax_box, ax_hist) = plt.subplots(
        nrows=2,
        sharex=True,
        gridspec_kw={"height_ratios": (0.25, 0.75)},
        figsize=figsize,
    )

    # boxplot
    sns.boxplot(x=df[feature], ax=ax_box, showmeans=True, color="lightgray")

    # histogram — only pass bins if not None
    if bins is not None:
        sns.histplot(df[feature], kde=kde, bins=bins, ax=ax_hist)
    else:
        sns.histplot(df[feature], kde=kde, ax=ax_hist)

    # reference lines
    ax_hist.axvline(df[feature].mean(), color="green", linestyle="--", label="Mean")
    ax_hist.axvline(df[feature].median(), color="black", linestyle="-", label="Median")
    ax_hist.legend()
    plt.tight_layout()
    plt.show()


# ============================================================
# A) UNIVARIATE ANALYSIS
# ============================================================
print("============================================================")
print("A) UNIVARIATE ANALYSIS")
print("============================================================\n")

# A.1 Target distribution
print("A.1 Target variable distribution (training data):")
if "Target" in data.columns:
    target_counts = data["Target"].value_counts(dropna=False)
    target_props  = data["Target"].value_counts(normalize=True, dropna=False)
    for cls in target_counts.index:
        print(f"- Class {int(cls)}: {target_counts[cls]} rows ({target_props[cls]*100:.2f}%)")
    print("\nInterpretation:")
    print("- Class 1 = failure.")
    print("- Class 0 = no failure.")
    print("- Class 1 is the minority class → we will need class weights / recall-aware metrics.\n")
else:
    print("- 'Target' column not found.\n")

# A.2 numeric features
numeric_cols = data.select_dtypes(include=[np.number]).columns.tolist()
if "Target" in numeric_cols:
    numeric_cols.remove("Target")

print("A.2 Numeric features identified:")
print(f"- Count (excluding Target): {len(numeric_cols)}")
print(f"- Example features: {numeric_cols[:10]}\n")

# A.3 missing values
print("A.3 Missing values in training data:")
train_missing = data.isnull().sum()
if train_missing.sum() == 0:
    print("- No missing values detected.\n")
else:
    # show only columns that actually have missing values
    display(train_missing[train_missing > 0])
    print()

# A.4 summary stats
print("A.4 Summary statistics of numeric features:")
display(data[numeric_cols].describe().T)
print()

# A.5 plot distributions
print("A.5 Distribution plots for numeric features")
print("    (This will generate one boxplot + histogram per numeric column.)\n")
for col in numeric_cols:
    print(f"Univariate distribution for: {col}")
    histogram_boxplot(data, col)


# ============================================================
# B) BIVARIATE ANALYSIS (WITH RESPECT TO TARGET)
# ============================================================
print("============================================================")
print("B) BIVARIATE ANALYSIS (with respect to Target)")
print("============================================================\n")

# B.1 feature means by target
print("B.1 Mean of numeric features by target class (training data):")
if "Target" in data.columns:
    grouped_means = data.groupby("Target")[numeric_cols].mean().T
    display(grouped_means)
    print("Notes:")
    print("- Columns with large differences between Target=0 and Target=1 are more discriminative.\n")
else:
    print("- Skipping: 'Target' column not found.\n")

# B.2 correlation heatmap
print("B.2 Correlation heatmap for numeric predictors (training data):")
corr_cols = data.select_dtypes(include=[np.number]).columns.tolist()
if "Target" in corr_cols:
    corr_cols.remove("Target")

plt.figure(figsize=(18, 18))
sns.heatmap(
    data[corr_cols].corr(),
    annot=False,
    cmap="Spectral",
    vmin=-1,
    vmax=1,
)
plt.title("Correlation Heatmap of Numeric Predictors")
plt.show()
print("Notes:")
print("- Strongly correlated features can be redundant.")
print("- This is mainly diagnostic here; the NN can still handle correlated inputs.\n")

# B.3 target distribution in test (to mirror train-side checks)
if "Target" in data_test.columns:
    print("B.3 Target distribution in the test data:")
    test_target_props = data_test["Target"].value_counts(normalize=True)
    for cls, prop in test_target_props.items():
        print(f"- Class {int(cls)}: {prop*100:.2f}%")
    print()
else:
    print("B.3 Test data does not contain 'Target' or is not available.\n")

print("EDA complete.")

"""### Data Preparation for Modeling

**Process:** Features and targets are separated, the original training data is split into train and validation sets, and missing values are imputed using the median fit on training data only.

**Outcome:** The saved run produces `X_train = (16000, 40)`, `X_val = (4000, 40)`, and `X_test = (5000, 40)`, with zero missing values remaining after imputation.
"""

# ------------------------------
# DATA PREPARATION FOR MODELING
# ------------------------------
# Creates train/val/test splits and imputes missing values (median, fit on train only).
# sklearn: train_test_split for splitting, SimpleImputer for median imputation.

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# 7.1 Separate features and target from the training data
X = data.drop(columns=["Target"])
y = data["Target"]

# 7.2 Create training and validation sets from the training data
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1,
    stratify=y,
)

print("7.1 Shapes after splitting original training data:")
print(f"- X_train: {X_train.shape}")
print(f"- X_val  : {X_val.shape}")

# 7.3 Prepare test features and target from the provided test data
X_test = data_test.drop(columns=["Target"])
y_test = data_test["Target"]

print(f"- X_test : {X_test.shape}\n")

# 7.4 Impute missing values using median (fit on train, apply to val/test)
imputer = SimpleImputer(strategy="median")
X_train = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns)
X_val   = pd.DataFrame(imputer.transform(X_val),   columns=X_train.columns)
X_test  = pd.DataFrame(imputer.transform(X_test),  columns=X_train.columns)

print("7.2 Missing values after imputation:")
print(f"- Train: {X_train.isnull().sum().sum()}")
print(f"- Val  : {X_val.isnull().sum().sum()}")
print(f"- Test : {X_test.isnull().sum().sum()}\n")

# 7.5 Convert targets to numpy arrays for Keras models
y_train = y_train.to_numpy()
y_val   = y_val.to_numpy()
y_test  = y_test.to_numpy()

print("Data preparation complete. Data is ready for model building.\n")

"""### **Modeling Utilities**

**Summary:** Standardized functions were constructed to dynamically compute evaluation metrics (accuracy, precision, recall, F1) and visualize epoch training curves.

**Observations:** The operational framework established enables uniform visual and statistical comparison across all future Neural Network iterations.

"""

# ------------------------------
# MODELING UTILITIES
# ------------------------------
# Defines reusable functions for classification metrics and training curve plots.

from sklearn.metrics import (
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    classification_report,
)

# Returns accuracy, recall, precision, F1 as a DataFrame.
def model_performance_classification(model, predictors, target, threshold=0.5):
    """
    Evaluate a binary classification model that outputs probabilities.
    Returns accuracy, recall, precision, and F1 score as a DataFrame.
    """
    y_prob = model.predict(predictors)
    y_pred = (y_prob > threshold).astype(int)

    acc  = accuracy_score(target, y_pred)
    rec  = recall_score(target, y_pred)
    prec = precision_score(target, y_pred)
    f1   = f1_score(target, y_pred)

    return pd.DataFrame(
        {
            "Accuracy": [acc],
            "Recall": [rec],
            "Precision": [prec],
            "F1 Score": [f1],
        }
    )


# Plots train vs. validation curves from Keras history.
def plot_history(history, metric_name):
    """
    Plot training vs validation metric curves from Keras history.
    """
    plt.figure()
    plt.plot(history.history[metric_name], label="Train")
    plt.plot(history.history["val_" + metric_name], label="Validation")
    plt.title(f"Model {metric_name.capitalize()}")
    plt.xlabel("Epochs")
    plt.ylabel(metric_name.capitalize())
    plt.legend()
    plt.show()

"""### Baseline Model (Model 0)

**Process:** A simple one-hidden-layer neural network is trained to establish the initial performance floor for the notebook.

**Analysis:** The baseline already achieves strong overall accuracy, but its lower recall on actual failures makes it insufficient as a final predictive-maintenance model where missed failures are expensive.

**Outcome:** Model 0 sets a strong numeric starting point but leaves clear room for recall-focused improvement.
"""

# ------------------------------
# BASELINE MODEL (MODEL 0)
# ------------------------------
# Single hidden layer (7 ReLU units), SGD optimizer — establishes the performance floor.
# tensorflow.keras: Sequential, Dense for model construction.

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

epochs = 50
batch_size = 32
input_dim = X_train.shape[1]

tf.keras.backend.clear_session()
model_0 = Sequential()
model_0.add(Dense(7, activation="relu", input_dim=input_dim))
model_0.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.SGD()
model_0.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_0 = model_0.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    verbose=0,
)

plot_history(history_0, "loss")

model_0_train_perf = model_performance_classification(model_0, X_train, y_train)
model_0_val_perf   = model_performance_classification(model_0, X_val, y_val)

print("Model 0 — Training performance")
display(model_0_train_perf)
print("\nModel 0 — Validation performance")
display(model_0_val_perf)

print("\nModel 0 — Classification report (validation)")
y_val_pred_0 = (model_0.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_0))

"""### Model 1 – Deeper Network

**Process:** A second hidden layer is added to test whether greater network depth improves failure detection.

**Analysis:** The deeper architecture improves recall materially over the baseline, but the notebook also shows stronger overfitting pressure in the validation-loss behavior.

**Outcome:** Model 1 demonstrates that added depth helps, but it is not yet the strongest final architecture.
"""

# ------------------------------
# MODEL 1 — DEEPER NETWORK
# ------------------------------
# Two hidden layers (32→16 ReLU), SGD — tests whether added depth helps.

tf.keras.backend.clear_session()
model_1 = Sequential()
model_1.add(Dense(32, activation="relu", input_dim=input_dim))
model_1.add(Dense(16, activation="relu"))
model_1.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.SGD()
model_1.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_1 = model_1.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    verbose=0,
)

plot_history(history_1, "loss")

model_1_train_perf = model_performance_classification(model_1, X_train, y_train)
model_1_val_perf   = model_performance_classification(model_1, X_val, y_val)

print("Model 1 — Training performance")
display(model_1_train_perf)
print("\nModel 1 — Validation performance")
display(model_1_val_perf)

print("\nModel 1 — Classification report (validation)")
y_val_pred_1 = (model_1.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_1))

"""### Model 2 – Regularized Network (Dropout)

**Process:** Dropout regularization is introduced to reduce overfitting in the deeper network.

**Analysis:** Regularization improves curve stability, but the saved metrics show a tradeoff: recall falls back relative to Model 1 even as precision remains strong.

**Outcome:** Model 2 improves generalization behavior but does not deliver the best failure-detection balance.
"""

# ------------------------------
# MODEL 2 — REGULARIZED (DROPOUT)
# ------------------------------
# Three hidden layers with Dropout(0.5) — reduces overfitting from deeper architecture.

from tensorflow.keras.layers import Dropout

tf.keras.backend.clear_session()
model_2 = Sequential()
model_2.add(Dense(32, activation="relu", input_dim=input_dim))
model_2.add(Dropout(0.5))
model_2.add(Dense(16, activation="relu"))
model_2.add(Dense(8, activation="relu"))
model_2.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.SGD()
model_2.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_2 = model_2.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    verbose=0,
)

plot_history(history_2, "loss")

model_2_train_perf = model_performance_classification(model_2, X_train, y_train)
model_2_val_perf   = model_performance_classification(model_2, X_val, y_val)

print("Model 2 — Training performance")
display(model_2_train_perf)
print("\nModel 2 — Validation performance")
display(model_2_val_perf)

print("\nModel 2 — Classification report (validation)")
y_val_pred_2 = (model_2.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_2))

"""### Class Weight Computation

**Process:** Inverse-frequency class weights are computed from the training data to increase the penalty for missing the minority failure class.

**Analysis:** The saved weights are heavily skewed toward the failure class, confirming that imbalance handling is necessary if the notebook is to prioritize missed-failure reduction.

**Outcome:** The notebook creates a weighting scheme that can push later models to pay more attention to true failures.
"""

# ------------------------------
# CLASS WEIGHT COMPUTATION
# ------------------------------
# Computes inverse-frequency weights so the model prioritizes the minority failure class.

class_counts = np.bincount(y_train.astype(int))
class_weights = (y_train.shape[0]) / class_counts
class_weight_dict = {i: class_weights[i] for i in range(len(class_weights))}

print("Class weights computed from training data:")
print(class_weight_dict)

"""### Model 3 – Regularized + Class Weights

**Process:** The regularized network is retrained using the computed class weights to improve sensitivity to turbine failures.

**Analysis:** Class weighting lifts recall relative to the dropout-only model, but the precision-recall balance still leaves room for a stronger final architecture.

**Outcome:** Model 3 confirms that imbalance-aware training moves the notebook closer to the right business objective.
"""

# ------------------------------
# MODEL 3 — REGULARIZED + CLASS WEIGHTS
# ------------------------------
# Same as Model 2 but trained with class weights to improve failure recall.

tf.keras.backend.clear_session()
model_3 = Sequential()
model_3.add(Dense(32, activation="relu", input_dim=input_dim))
model_3.add(Dropout(0.5))
model_3.add(Dense(16, activation="relu"))
model_3.add(Dense(8, activation="relu"))
model_3.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.SGD()
model_3.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_3 = model_3.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    class_weight=class_weight_dict,
    verbose=0,
)

plot_history(history_3, "loss")

model_3_train_perf = model_performance_classification(model_3, X_train, y_train)
model_3_val_perf   = model_performance_classification(model_3, X_val, y_val)

print("Model 3 — Training performance")
display(model_3_train_perf)
print("\nModel 3 — Validation performance")
display(model_3_val_perf)

print("\nModel 3 — Classification report (validation)")
y_val_pred_3 = (model_3.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_3))

"""### Model 4 – Change Optimizer to Adam

**Process:** The optimizer is changed from SGD to Adam to test whether adaptive learning improves convergence and failure detection.

**Analysis:** Adam materially improves validation performance, especially on recall and F1, but the notebook still shows overfitting pressure in the validation-loss behavior.

**Outcome:** Model 4 becomes a strong candidate and establishes Adam as the more effective optimizer for this problem.
"""

# ------------------------------
# MODEL 4 — ADAM OPTIMIZER
# ------------------------------
# Two hidden layers with Adam — tests whether adaptive learning rates improve convergence.

tf.keras.backend.clear_session()
model_4 = Sequential()
model_4.add(Dense(32, activation="relu", input_dim=input_dim))
model_4.add(Dense(16, activation="relu"))
model_4.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.Adam()
model_4.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_4 = model_4.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    verbose=0,
)

plot_history(history_4, "loss")

model_4_train_perf = model_performance_classification(model_4, X_train, y_train)
model_4_val_perf   = model_performance_classification(model_4, X_val, y_val)

print("Model 4 — Training performance")
display(model_4_train_perf)
print("\nModel 4 — Validation performance")
display(model_4_val_perf)

print("\nModel 4 — Classification report (validation)")
y_val_pred_4 = (model_4.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_4))

"""### Model 5 – Deeper Network with Dropout (Adam)

**Process:** A deeper architecture is combined with dropout and Adam to capture the strongest elements from earlier experiments.

**Analysis:** Model 5 delivers the strongest overall data profile in the notebook over successive runs: strong validation performance, high precision, stable convergence, and the clearest held-out test confirmation.  It is the best current deployment candidate and the strongest foundation for further development.

**Outcome:** Model 5 becomes the selected lead model and is advanced to held-out test evaluation performed best over successive runs.
"""

# ------------------------------
# MODEL 5 — DEEPER + DROPOUT + ADAM
# ------------------------------
# Three hidden layers (64→32→16), Dropout, Adam — combines the strongest elements.

tf.keras.backend.clear_session()
model_5 = Sequential()
model_5.add(Dense(64, activation="relu", input_dim=input_dim))
model_5.add(Dropout(0.5))
model_5.add(Dense(32, activation="relu"))
model_5.add(Dense(16, activation="relu"))
model_5.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.Adam()
model_5.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_5 = model_5.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    verbose=0,
)

plot_history(history_5, "loss")

model_5_train_perf = model_performance_classification(model_5, X_train, y_train)
model_5_val_perf   = model_performance_classification(model_5, X_val, y_val)

print("Model 5 — Training performance")
display(model_5_train_perf)
print("\nModel 5 — Validation performance")
display(model_5_val_perf)

print("\nModel 5 — Classification report (validation)")
y_val_pred_5 = (model_5.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_5))

"""### Model 6 – Deeper + Class Weights (SGD)

**Process:** A deeper class-weighted architecture is trained under SGD to test whether a more recall-oriented setup can outperform Model 5.

**Analysis:** On initial numbers, Model 6 can appear stronger because it posts the highest saved validation recall and F1. However, those results vary across successive runs, and Model 6 is not carried through the same held-out test evaluation in the current notebook. That makes it the strongest challenger, not the lead model.

**Outcome:** Model 6 remains the most important recall-oriented alternative and the model most worth continued development alongside Model 5.
"""

# ------------------------------
# MODEL 6 — DEEPER + CLASS WEIGHTS (SGD)
# ------------------------------
# Same depth as Model 5 but with SGD and class weights — tests optimizer-imbalance interaction.

tf.keras.backend.clear_session()
model_6 = Sequential()
model_6.add(Dense(64, activation="relu", input_dim=input_dim))
model_6.add(Dropout(0.5))
model_6.add(Dense(32, activation="relu"))
model_6.add(Dense(16, activation="relu"))
model_6.add(Dense(1, activation="sigmoid"))

optimizer = tf.keras.optimizers.SGD()
model_6.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history_6 = model_6.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=epochs,
    batch_size=batch_size,
    class_weight=class_weight_dict,
    verbose=0,
)

plot_history(history_6, "loss")

model_6_train_perf = model_performance_classification(model_6, X_train, y_train)
model_6_val_perf   = model_performance_classification(model_6, X_val, y_val)

print("Model 6 — Training performance")
display(model_6_train_perf)
print("\nModel 6 — Validation performance")
display(model_6_val_perf)

print("\nModel 6 — Classification report (validation)")
y_val_pred_6 = (model_6.predict(X_val) > 0.5).astype(int)
print(classification_report(y_val, y_val_pred_6))

"""### Model Performance Comparison

**Process:** Training and validation metrics for all seven models are assembled into side-by-side comparison tables.

**Analysis:** On initial comparison numbers, **Model 6** can look stronger because it pushes recall slightly higher. However, run-to-run variability matters, and **Model 5** has the stronger overall data profile: it combines strong validation performance, better current deployment evidence, and actual held-out test confirmation. That makes Model 5 the better current deployment candidate and the model with the strongest foundation for further development.

**Outcome:** Model 5 remains the lead model for current deployment, while Model 6 remains the most important challenger for recall-oriented improvement.
"""

# ------------------------------
# MODEL PERFORMANCE COMPARISON
# ------------------------------
# Aggregates train and validation metrics for all seven models into side-by-side tables.

train_perf_comp = pd.concat(
    [
        model_0_train_perf.T,
        model_1_train_perf.T,
        model_2_train_perf.T,
        model_3_train_perf.T,
        model_4_train_perf.T,
        model_5_train_perf.T,
        model_6_train_perf.T,
    ],
    axis=1,
)
train_perf_comp.columns = [
    "Model 0",
    "Model 1",
    "Model 2",
    "Model 3",
    "Model 4",
    "Model 5",
    "Model 6",
]

val_perf_comp = pd.concat(
    [
        model_0_val_perf.T,
        model_1_val_perf.T,
        model_2_val_perf.T,
        model_3_val_perf.T,
        model_4_val_perf.T,
        model_5_val_perf.T,
        model_6_val_perf.T,
    ],
    axis=1,
)
val_perf_comp.columns = [
    "Model 0",
    "Model 1",
    "Model 2",
    "Model 3",
    "Model 4",
    "Model 5",
    "Model 6",
]

print("Training set performance comparison:")
display(train_perf_comp)

print("Validation set performance comparison:")
display(val_perf_comp)

"""### Test Set Evaluation

**Process:** The selected best model, Model 5, is evaluated on the held-out test set to confirm generalization beyond validation performance.

**Analysis:** On the saved test run, Model 5 achieves **0.9916** accuracy, **0.868794** recall, **0.98** precision, and **0.921053** F1, confirming that it preserves strong failure detection while keeping false alarms tightly controlled.

**Outcome:** Model 5 generalizes well on unseen data and is validated as the notebook’s current lead deployment model.
"""

# ------------------------------
# TEST SET EVALUATION
# ------------------------------
# Evaluates the selected best model on the held-out test set to confirm generalization.

best_model = model_5  # update this if another model performs better

test_perf = model_performance_classification(best_model, X_test, y_test)
print("Test set performance for the selected model:")
display(test_perf)

print("\nClassification report — test set")
y_test_pred = (best_model.predict(X_test) > 0.5).astype(int)
print(classification_report(y_test, y_test_pred))

"""### **Expanded Executive Summary**

**TLDR**

**Model 5** is the strongest current commercial model because it catches **86.88%** of turbine failures on the held-out test set while maintaining **98.0% precision**. In business terms, that means it can support intervention on roughly **87 out of every 100 real failures**, pointing to a theoretical protected replacement-exposure range of approximately **\$217.5M–\$348M per 100 true failures**, before counting downtime savings. **Model 6** should still be developed if implemented at the enterprise level because its stronger initial recall suggests it could outpreform model 5 in the longrun as well.

**Full Summary**

**Objective:** This project built a predictive-maintenance DNN workflow to identify wind turbine failures before breakdown, allowing operators to shift from reactive replacement toward planned intervention. The business case is direct: preventing even a small number of missed failures can avoid **\$2.5M–\$4M** replacement exposure per turbine and reduce downtime losses that can reach **\$17,000 per day**.

**Iterative Development:** Seven DNN configurations were tested across changes in architecture depth, dropout, class weighting, and optimizer choice. The objective was not simply to maximize accuracy, but to find the best operational balance between catching true failures early and avoiding unnecessary maintenance activity driven by false alarms.

**Performance Analysis:** On initial comparison numbers, **Model 6** can appear stronger because it posts the highest saved validation recall and F1. However, model rankings can vary across successive runs, and **Model 5** has the strongest overall data profile because it combines strong validation performance with the clearest deployment evidence: On held-out test evaluation in the current notebook, **Model 5** achieves **99.16% accuracy**, **86.88% recall**, **98.0% precision**, and **0.921 F1**, making it the strongest current deployment choice. The correct interpretation is not that Model 6 is irrelevant, but that **Model 5 is the proven lead model today, while Model 6 is the most credible upside challenger**.

**Economic Impact:** The commercial value of this system comes from converting detection quality into avoided loss exposure. With **86.88% recall**, **Model 5** can theoretically identify about **87 out of every 100 actual turbine failures** before breakdown. Using the notebook’s stated replacement-cost range, that implies approximately **\$217.5M–\$348M** in protected replacement exposure per 100 true failures, before counting the additional benefit of avoided downtime. Precision matters just as much operationally: at **98.0% precision**, the model generates only about **2 false alarms per 100 alerts**, which helps contain unnecessary inspection and maintenance cost. This is why **Model 5** is the stronger current commercial choice: it protects substantial recoverable value while keeping operational noise low.

**Deployment Readiness:** **Model 5** should be treated as the primary deployment track for integration into predictive-maintenance dashboards, maintenance-prioritization workflows, and operational alerting systems. It is the strongest current model for commercial pilots because it combines high failure capture with very strong false-alarm control. For an enterprise organization, **Model 6** should continue to be developed in parallel because its stronger initial recall suggests additional recoverable value if that advantage can be confirmed on equivalent held-out test evaluation and improved without materially weakening precision. The right enterprise strategy is therefore clear: **deploy Model 5, develop Model 6**.

**Next Steps:** Run the same held-out test-set evaluation on **Model 6** that was used for **Model 5** to confirm whether its higher initial recall can unlock greater recoverable value on equivalent evidence without creating excessive false-alarm cost.
"""