# -*- coding: utf-8 -*-
"""medical_diagnosis_assist__qa__rag_exp_(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgyCTGYd5JWKpVZSXINudCUSppbSd7En

PROTOTYPE
# **Medical Diagnostic Assistant**: AI-Powered RAG

---

## **Value Proposition**

In order to reduce the risk of AI-generated medical hallucinations a RAG system grounded in The Merck Manual was developed that constrains clinical responses to verified source material, achieving average groundedness scores of 4.8/5 across 9 validated clinical queries.

---

## **Executive Summary**


### Business Opportunities

* **Opportunity A:** AI hallucinations in healthcare create unacceptable clinical risk. Unconstrained LLMs produce fluent but unverifiable medical guidance that cannot be safely deployed.

* **Solution A:** The RAG architecture constrains all generated responses to content retrieved from The Merck Manual, ensuring every answer is traceable to an authoritative source.

* **Opportunity B:** Healthcare professionals face increasing information overload, struggling to synthesize vast volumes of medical data under time pressure.

* **Solution B:** The system retrieves relevant passages and generates structured clinical responses in seconds, reducing manual search effort and promoting diagnostic consistency.

* **Opportunity C:** Multiple integration paths exist for this system across healthcare and clinical decision-support markets.

* **Solution C** (Options): Internal clinical decision-support dashboard for diagnostic teams. API integration into electronic health record (EHR) systems. Mobile reference tool for emergency and field medicine providers.


### Outcomes

* **Model Performance**

  * RAG system achieved average groundedness scores of 4.8/5 and relevance scores of 4.8/5 across 9 clinical queries.

  * Baseline (ungrounded) LLM produced fluent but unverifiable responses with no source traceability.

* **Architecture**

  * Retrieval-Augmented Generation with k=3 top chunks at temperature 0.1 produces the most deterministic, traceable answers.

  * LLM-as-judge evaluation framework provides automated quality scoring without manual clinical review.

* **Economic Impact**

  * Reducing clinical information retrieval time and promoting consistency in diagnostic reasoning directly translates to operational efficiency gains and reduced clinical risk.

* **Strategy Recommendation**

  * Enterprise: Deploy as a clinical decision-support tool integrated into existing EHR workflows, with audit logging for compliance.

  * SMB: Offer as a standalone reference application for smaller practices and field clinicians requiring rapid, grounded medical guidance.


---

## **Problem Space**


### Overview

* Healthcare professionals face information overload, struggling to synthesize vast medical literature under time pressure.

* Unconstrained AI models risk producing fluent but unsupported medical guidance — a critical liability in clinical settings.

* Grounding AI responses in authoritative sources (e.g., The Merck Manual) ensures traceability and clinical reliability.


### Data Description

* The Merck Manual of Diagnosis & Therapy — over 4,000 pages of structured medical content covering disorders, tests, diagnoses, and drugs.

* Provided as PDF: `014-NLP-PROJ-medical_diagnosis_manual_19.pdf`.

### Clinical Queries Evaluated

1. Diagnostic Assistance: Pulmonary embolism symptoms and treatments
2. Surgical Inquiry: Appendicitis symptoms, medicine vs. surgical treatment
3. Drug Information: Trade names of hypertension medications
4. Treatment Plans: Rheumatoid arthritis first-line options and alternatives
5. Dermatology: Sudden patchy hair loss causes and treatments
6. Neurology: Brain injury treatment recommendations
7. Emergency Care: Leg fracture precautions and treatment steps
8. Specialty Knowledge: Diagnostic steps for endocrine disorders
9. Critical Care Protocols: Sepsis management in critical care

### Process

* A baseline ungrounded LLM was evaluated for fluency, then prompt engineering was tested for formatting improvements.
* The Merck Manual was chunked, embedded, and indexed into a FAISS vector store for semantic retrieval.
* RAG generation was optimized across k-values and temperature settings, with final configuration at k=3, temp=0.1.
* Automated evaluation via LLM-as-judge scored responses on groundedness and relevance (1–5 scale).

### Results
>| Model | Groundedness | Relevance | Traceability |
>|---|---|---|---|
>| Model 1: Baseline LLM (Ungrounded) | Low | Medium | None |
>| **Model 2: RAG LLM (k=3, temp=0.1) ✅** | **4.8/5** | **4.8/5** | **Full** |


### Next Steps
* Broaden the reference corpus with additional peer-reviewed medical literature and specialty-specific guidelines.
* Adopt domain-specialized embeddings to improve semantic accuracy for nuanced clinical terminology.
* Deploy a front-end dashboard enabling clinicians to submit queries, view answers alongside cited excerpts, and inspect quality scores.
* Pilot deployment with a limited cohort of healthcare professionals to validate usability and workflow impact.

# **Execute Code**
*   Installing Colab Dependecies may require a Runtime restart. You will be notified if a restart is required
*   Data cited in markdown cells may differ sligntly from outputs, as training data and test data are randomized

## Environment Initialization

### Environment Setup and Dependency Configuration

**Outcome:** A runtime capable of fast local inference and large-scale medical document retrieval is available.

**Process:** GPU-enabled llama-cpp is installed for efficient execution of a quantized instruction-tuned model, alongside libraries required for PDF ingestion, embedding generation, and vector search.
"""

import os
from pathlib import Path
from IPython.display import display, HTML

# Set flags for llama-cpp-python to compile with CUDA support for faster local inference
os.environ["CMAKE_ARGS"] = "-DLLAMA_CUBLAS=on"
os.environ["FORCE_CMAKE"] = "1"

flag_file = Path("/content/.deps_installed_flag")

if not flag_file.exists():
    print("Installing dependencies... This may take a minute or two.")

    # Safely install dependencies, suppressing output and error warnings
    !pip install -q llama-cpp-python==0.2.28 > /dev/null 2>&1
    !pip install -q huggingface_hub pandas tiktoken pymupdf langchain langchain-community langchain-text-splitters chromadb sentence-transformers transformers > /dev/null 2>&1

    # Set the persistent flag so this block skips after restarting
    flag_file.touch()

    display(HTML("""
    <div style="
        border: 4px solid #d93025;
        background: #fce8e6;
        color: #202124;
        padding: 24px;
        border-radius: 12px;
        font-family: Arial, sans-serif;
        margin: 16px 0;
    ">
        <div style="font-size: 30px; font-weight: 800; color: #b31412; margin-bottom: 12px;">
            ⚠️ Runtime Restart Required
        </div>
        <div style="font-size: 22px; line-height: 1.5; font-weight: 600;">
            Dependencies have been successfully installed!
            <br><br>
            Please go to <b>Runtime → Restart session and run all</b> in the top menu.
        </div>
    </div>
    """))
else:
    print("✅ Dependencies already installed. No restart required.")

"""**Note:** Please restart the runtime after installation.

### Core Imports and Shared Configuration

**Outcome:** All execution paths operate on consistent dependencies and shared configuration.

**Process:** Common libraries are imported once so baseline, tuned, and retrieval-augmented runs use identical primitives and inputs.
"""

# ============================================================
# Core Imports and Shared Configuration
# ============================================================

import os  # for filesystem checks and local path handling
import pandas as pd  # for tabular result handling and evaluation outputs
from huggingface_hub import hf_hub_download  # for downloading the quantized GGUF model from Hugging Face
from llama_cpp import Llama  # for local LLM inference using llama-cpp
from langchain_text_splitters import RecursiveCharacterTextSplitter  # for chunking long medical text into retrieval units
from langchain_community.document_loaders import PyMuPDFLoader  # for loading the medical reference PDF into documents
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings  # for converting chunks into embeddings
from langchain_community.vectorstores import Chroma  # for storing and retrieving embedded chunks

# Global Qs
questions = [
    "What are the common symptoms and treatments for pulmonary embolism?",
    "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?",
    "Can you provide the trade names of medications used for treating hypertension?",
    "What are the first-line options and alternatives for managing rheumatoid arthritis?",
    "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?",
    "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?",
    "What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?",
    "What are the diagnostic steps for suspected endocrine disorders?",
    "What is the protocol for managing sepsis in a critical care unit?"
]

"""## Baseline Medical Question Answering (Ungrounded)

### Baseline Model Initialization

**Outcome:** An ungrounded medical question-answering baseline is established for comparison.

**Process:** A quantized Mistral-7B Instruct model is loaded locally without external reference constraints.
"""

# ============================================================
# Load and Initialize LLM
# ============================================================


# Load LLM
model_name_or_path = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_basename = "mistral-7b-instruct-v0.2.Q4_K_M.gguf"

model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

# Initialize LLM
llm = Llama(
    model_path=model_path,
    n_ctx=4096,        # Context window
    n_gpu_layers=-1,   # Offload all to GPU suitable for T4
    n_batch=512,
    verbose=True
)

"""###Inference Wrapper

**Outcome:** Inference behavior is standardized for repeatability and comparison.

**Process:** Prompt construction and decoding parameters are encapsulated in a single reusable function.
"""

# ============================================================
# Inference Wrapper
# ============================================================

def generate_response(query, max_tokens=2048, temperature=0.1, top_p=0.95, top_k=50, system_prompt=None):
    if system_prompt:
        prompt = f"[INST] {system_prompt}\n{query} [/INST]"
    else:
        prompt = f"[INST] {query} [/INST]"

    model_output = llm(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k
    )
    return model_output['choices'][0]['text'].strip()

"""### Baseline Question Execution

**Outcome:** Ungrounded model behavior is measured across the full medical question set.

**Process:** All questions are executed against the baseline model to surface systematic behaviors rather than isolated examples.
"""

# ============================================================
# Baseline Question Execution
# ============================================================

vanilla_results = []
for i, q in enumerate(questions, 1):
    print(f"--- Question {i} ---")
    print(f"Q: {q}")
    ans = generate_response(q)
    print(f"A: {ans}\n")
    vanilla_results.append(ans)

"""### Baseline Analysis

Ungrounded responses demonstrate fluent medical language and generally correct high-level framing. However, outputs cannot guarantee alignment with reference standards, cannot reliably signal missing or incomplete evidence, and may imply unsupported specificity. This establishes the risk profile that motivates subsequent constraint and grounding steps.

## Prompt Engineering and Decoding Control (Parameter Tuning)

### Prompt Configuration Evaluation

**Outcome:** Response consistency and professional tone are improved without altering evidentiary constraints.

**Process:** Multiple system prompts and decoding configurations are evaluated to control verbosity, determinism, and structural clarity.
"""

# ============================================================
# Prompt Configuration Evaluation
# ============================================================

# Define 5 Configurations

configs = [
    {"name": "High Creativity", "temp": 0.9, "sys": "You are a helpful medical assistant.", "top_k": 100},
    {"name": "Strict Professional", "temp": 0.0, "sys": "You are a concise, professional doctor. Answer only what is asked.", "top_k": 10},
    {"name": "Chain of Thought", "temp": 0.3, "sys": "Think step-by-step. Explain the reasoning before giving the final answer.", "top_k": 40},
    {"name": "ELI5", "temp": 0.7, "sys": "Explain like I am 5 years old.", "top_k": 50},
    {"name": "Balanced", "temp": 0.4, "sys": "You are a knowledgeable assistant. Provide detailed clinical information.", "top_k": 50}
]

# We will test these on all questions
for q_idx, question in enumerate(questions, 1):
    print(f"\n=== Testing Question {q_idx} ===")
    print(f"Q: {question}\n")

    for cfg in configs:
        print(f"--- {cfg['name']} ---")
        ans = generate_response(
            question,
            temperature=cfg['temp'],
            top_k=cfg['top_k'],
            system_prompt=cfg['sys']
        )
        print(f"{ans}\n")

"""### Prompting Analysis

Prompt discipline improves presentation quality and repeatability, particularly under low-temperature configurations. These changes affect form rather than substance; responses remain unconstrained with respect to source fidelity, reinforcing that prompt engineering alone does not address hallucination risk.

## Reference Preparation for Retrieval-Augmented Generation

### Reference Document Ingestion

**Outcome:** An authoritative medical reference is loaded as the sole evidence source.

**Process:** The Merck Manual PDF is auto-loaded from the managed GitHub dataset package and validated for downstream processing.
"""

# ============================================================
# Reference Document Ingestion
# ============================================================

import importlib.util  # for loading the shared data access helper dynamically
import shutil  # for clearing stale notebook-specific cached dataset folders
import sys  # for detecting whether the notebook is running in Colab
import urllib.request  # for downloading the shared helper file from GitHub
from pathlib import Path  # for cross-platform file path handling
from langchain_community.document_loaders import PyMuPDFLoader  # for parsing the PDF into page-level documents

HELPER_URL = "https://raw.githubusercontent.com/EvagAIML/000-website-notebooks/main/notebooks/_shared/data_access.py"

SLUG = "medical-diagnosis-assist__qa__rag-exp"
EXTRACT_TO = "medical-diagnosis-assist__qa__rag-exp__dataset__v1"
ZIP_NAME = "medical-diagnosis-assist__qa__rag-exp__dataset__v1.zip"

helper_path = Path("/content/data_access.py") if "google.colab" in sys.modules else Path("./data_access.py")
cache_root = Path("/content/data_cache") if "google.colab" in sys.modules else Path("./data_cache")
session_flag = Path("/content/.medical_cache_refreshed") if "google.colab" in sys.modules else Path(".medical_cache_refreshed")

# Clear stale notebook-specific artifacts once per fresh session
if not session_flag.exists():
    helper_path.unlink(missing_ok=True)
    shutil.rmtree(cache_root / EXTRACT_TO, ignore_errors=True)
    (cache_root / ZIP_NAME).unlink(missing_ok=True)
    session_flag.touch()

urllib.request.urlretrieve(HELPER_URL, helper_path)

spec = importlib.util.spec_from_file_location("data_access", helper_path)
data_access = importlib.util.module_from_spec(spec)
spec.loader.exec_module(data_access)

ensure_dataset = data_access.ensure_dataset

DATA_DIR = ensure_dataset(SLUG)
RAW_DIR = DATA_DIR / "raw"
doc_path = RAW_DIR / "medical_diagnosis_manual.pdf"

loader = PyMuPDFLoader(str(doc_path))
docs = loader.load()
print(f"Loaded {len(docs)} pages from {doc_path.name}.")

# Check first 5 pages
for i in range(min(5, len(docs))):
    print(f"--- Page {i+1} ---")
    print(docs[i].page_content[:500])
    print("...")

"""### Reference Text Chunking

**Outcome:** Reference content is prepared for reliable semantic retrieval.

**Process:** Text is segmented into overlapping chunks to preserve clinical context across boundaries.
"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)
chunks = text_splitter.split_documents(docs)
print(f"Total Chunks created: {len(chunks)}")

"""### Vector Index Construction

**Outcome:** Reference knowledge is indexed for low-latency similarity search.

**Process:** Chunks are embedded and persisted in a vector database to enable efficient retrieval at query time.
"""

# ============================================================
# Embedding & Vector Store
# ============================================================

from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings

embedding_model = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    persist_directory="./chroma_db_medical_final"
)

# Default Retriever
retriever = vector_db.as_retriever(search_kwargs={"k": 3})

"""### Retrieval Preparation Analysis

Retrieval quality becomes the dominant factor in answer reliability. Chunk size, overlap, and embedding fidelity directly influence whether relevant clinical guidance is surfaced and whether the model remains constrained to appropriate evidence.

## Retrieval-Augmented Medical Question Answering

### RAG Answer Generation

**Outcome:** Medical answers are constrained to verifiable reference material.

**Process:** Relevant passages are retrieved per query and injected into the generation prompt, restricting synthesis to supplied evidence.
"""

# ============================================================
# RAG Generation Function
# ============================================================

def generate_rag_answer(query, k=3, temperature=0.1, max_tokens=2048):
    # Retrieve
    retrieved_docs = vector_db.similarity_search(query, k=k)

    # Format context and extract sources
    context_list = []
    sources_info = []
    for d in retrieved_docs:
        page_num = d.metadata.get('page', 'Unknown')
        # Assuming page is 0-indexed integer from PyMuPDF
        if isinstance(page_num, int):
            page_num += 1
        src_str = f"Page {page_num}"
        sources_info.append(src_str)
        context_list.append(f"[{src_str}] {d.page_content}")

    context = "\n\n".join(context_list)
    unique_sources = ", ".join(sorted(list(set(sources_info))))

    # Construct Prompt
    sys_msg = "You are a professional medical assistant for healthcare professionals. Use the following Context to answer the Question. If the answer is not in the context, say so. Do not advise consulting a healthcare professional."
    user_msg = f"Context:\n{context}\n\nQuestion: {query}\n\nPlease cite specific Page numbers and Sections from the text in your answer."

    prompt = f"[INST] {sys_msg}\n{user_msg} [/INST]"

    # Generate
    output = llm(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        stop=["[/INST]"]
    )
    return output['choices'][0]['text'].strip(), context

# ============================================================
# RAG Parameter Tuning (5 Combinations)
# ============================================================

rag_configs = [
    {"name": "C1: Low Context, Precise", "k": 2, "temp": 0.0},
    {"name": "C2: Standard", "k": 3, "temp": 0.1},
    {"name": "C3: High Context", "k": 5, "temp": 0.1},
    {"name": "C4: Creative", "k": 3, "temp": 0.7},
    {"name": "C5: Max Context, Strict", "k": 7, "temp": 0.0}
]

print("Running RAG Tuning on all questions")
for q_idx, question in enumerate(questions, 1):
    print(f"\n=== RAG Tuning Question {q_idx} ===")
    print(f"Q: {question}\n")

    for cfg in rag_configs:
        print(f"--- {cfg['name']} ---")
        ans, _ = generate_rag_answer(question, k=cfg['k'], temperature=cfg['temp'])
        print(f"A: {ans}\n")

"""### Grounded Question Execution

**Outcome:** Evidence-backed answers and supporting context are produced for all queries to determine best K and temp value.

**Process:** Responses are generated alongside retrieved passages to support review, auditability, and evaluation.

### Final RAG Answers (Best Configuration: k=3, temp=0.1)
"""

# ============================================================
# Final RAG Configuration -> Answers
# ============================================================

rag_responses = []
rag_contexts = []

for i, q in enumerate(questions, 1):
    print(f"--- RAG Question {i} ---")
    print(f"Q: {q}")
    ans, ctx = generate_rag_answer(q, k=3, temperature=0.1)
    print(f"A: {ans}\n")
    rag_responses.append(ans)
    rag_contexts.append(ctx)

"""### RAG Analysis

When retrieval surfaces relevant passages, responses remain tightly aligned with reference language, scope, and limitations. When retrieval is weak or incomplete, answer quality degrades proportionally, highlighting the importance of retrieval tuning and prompt discipline.

Reason for selecting k=3, temp=0.1:
- **Specificity:** The answers are now directly referencing information found in the Merck Manual chunks.
- **Reduced Hallucination:** When asked about trade names (Q2), if the chunks do not contain them, the model is more likely to stick to what is present (generic names) or state limitations, rather than inventing names.
- **Context:** Increasing `k` helps when the answer is spread across multiple sections, but too high `k` can introduce noise.

## Automated Output Evaluation (LLM as the judge)

### Response Scoring

**Outcome:** Answer quality is measured objectively and at scale for goundedness and relevance (1-5).

**Process:** Using prompt LLM prompts, responses are scored for groundedness and relevance using machine-parseable output that explains the reason for a score.
"""

# ============================================================
# Response Evaluation (Refined 1-5 Scoring with evidence)
# ============================================================

import re

groundedness_rater_system_message = """
You are tasked with rating AI generated answers to questions posed by users.
You will be presented a question, context used by the AI system to generate the answer and an AI generated answer to the question.
In the input, the question will begin with ###Question, the context will begin with ###Context while the AI generated answer will begin with ###Answer.

Evaluation criteria:
The task is to judge the extent to which the metric is followed by the answer.
1 - The metric is not followed at all
2 - The metric is followed only to a limited extent
3 - The metric is followed to a good extent
4 - The metric is followed mostly
5 - The metric is followed completely

Metric:
The answer should be derived only from the information presented in the context

Instructions:
1. First write down the steps that are needed to evaluate the answer as per the metric.
2. Give a step-by-step explanation if the answer adheres to the metric considering the question and context as the input.
3. Next, evaluate the extent to which the metric is followed.
4. Use the previous information to rate the answer using the evaluaton criteria and assign a score.
5. IMPORTANT: End your response with a single line: SCORE: X (where X is 1, 2, 3, 4, or 5)
"""

relevance_rater_system_message = """
You are tasked with rating AI generated answers to questions posed by users.
You will be presented a question, context used by the AI system to generate the answer and an AI generated answer to the question.
In the input, the question will begin with ###Question, the context will begin with ###Context while the AI generated answer will begin with ###Answer.

Evaluation criteria:
The task is to judge the extent to which the metric is followed by the answer.
1 - The metric is not followed at all
2 - The metric is followed only to a limited extent
3 - The metric is followed to a good extent
4 - The metric is followed mostly
5 - The metric is followed completely

Metric:
Relevance measures how well the answer addresses the main aspects of the question, based on the context.
Consider whether all and only the important aspects are contained in the answer when evaluating relevance.

Instructions:
1. First write down the steps that are needed to evaluate the context as per the metric.
2. Give a step-by-step explanation if the context adheres to the metric considering the question as the input.
3. Next, evaluate the extent to which the metric is followed.
4. Use the previous information to rate the context using the evaluaton criteria and assign a score.
5. IMPORTANT: End your response with a single line: SCORE: X (where X is 1, 2, 3, 4, or 5)
"""

def evaluate_response(query, answer, context):
    # Groundedness Prompt
    ground_prompt = f"[INST] {groundedness_rater_system_message}\n\n###Question\n{query}\n###Context\n{context}\n###Answer\n{answer}\n[/INST]"

    # Use Main LLM (Mistral)
    ground_out = llm(ground_prompt, max_tokens=512, temperature=0.1)['choices'][0]['text'].strip()

    # Relevance Prompt
    rel_prompt = f"[INST] {relevance_rater_system_message}\n\n###Question\n{query}\n###Context\n{context}\n###Answer\n{answer}\n[/INST]"

    # Use Main LLM (Mistral)
    rel_out = llm(rel_prompt, max_tokens=512, temperature=0.1)['choices'][0]['text'].strip()

    # Parse Scores using Regex (Prioritize explicit format)
    def parse_score(text):
        # Try strict format first: SCORE: 5
        strict_matches = re.findall(r'SCORE:\s*([1-5])', text, re.IGNORECASE)
        if strict_matches:
            return int(strict_matches[-1])

        # Fallback: Look for last digit 1-5
        matches = re.findall(r'\b([1-5])\b', text)
        if matches:
            return int(matches[-1])
        return 0 # Error or not found

    ground_score = parse_score(ground_out)
    rel_score = parse_score(rel_out)

    return ground_score, ground_out, rel_score, rel_out

print("--- Evaluation Results ---\n")

eval_results_data = [] # We save the scores here so the UI cell can read them instantly

for i, (q, a, c) in enumerate(zip(questions, rag_responses, rag_contexts), 1):
    gs, ge, rs, re_text = evaluate_response(q, a, c)

    eval_results_data.append({
        "groundedness_score": gs,
        "relevance_score": rs
    })

    print(f"Q{i}: {q}")
    print(f"Groundedness Score: {gs}/5")
    print(f"Reason: {ge}")
    print(f"Relevance Score: {rs}/5")
    print(f"Reason: {re_text}")
    print("-" * 50)

import pandas as pd
from IPython.display import display, HTML

# 1. Structure the data for frontend use (List of Dictionaries / DataFrame)
frontend_data = []

# Fallback in case eval_results_data wasn't generated yet
if 'eval_results_data' not in globals() or len(eval_results_data) != len(questions):
    eval_results_data = [{"groundedness_score": "N/A", "relevance_score": "N/A"} for _ in range(len(questions))]

for i, (q, a, c, e) in enumerate(zip(questions, rag_responses, rag_contexts, eval_results_data), 1):
    frontend_data.append({
        "id": i,
        "question": q,
        "answer": a,
        "context": c,
        "groundedness_score": e["groundedness_score"],
        "relevance_score": e["relevance_score"]
    })

# Convert to DataFrame for structured tabular use or JSON export later
results_df = pd.DataFrame(frontend_data)

# 2. Present in a readable, good-looking HTML UI
html_str = """
<style>
    .qa-card { border: 1px solid #e0e0e0; border-radius: 8px; margin-bottom: 16px; padding: 16px; font-family: sans-serif; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    .qa-question { font-size: 1.1em; font-weight: bold; color: #1a73e8; margin-bottom: 12px; }
    .qa-answer { background-color: #f1f3f4; padding: 12px; border-left: 4px solid #1a73e8; border-radius: 0 4px 4px 0; margin-bottom: 12px; color: #202124; line-height: 1.5; }
    .qa-scores { margin-bottom: 12px; font-size: 0.95em; }
    .score-badge { display: inline-block; padding: 4px 8px; border-radius: 12px; font-weight: bold; margin-right: 8px; }
    .score-high { background-color: #ceead6; color: #0d652d; }
    .score-med { background-color: #fef7e0; color: #b06000; }
    .qa-context-summary { cursor: pointer; color: #188038; font-weight: 500; user-select: none; }
    .qa-context { background-color: #e6f4ea; padding: 12px; border-radius: 4px; font-size: 0.9em; margin-top: 8px; color: #137333; white-space: pre-wrap; line-height: 1.4; }
</style>
<div style="max-width: 950px; margin: 0 auto;">
    <h2 style="font-family: sans-serif; color: #202124;">RAG Diagnostic Results & Evaluation</h2>
    <p style="font-family: sans-serif; color: #5f6368;">
        Structured output ready for API/Frontend consumption. Includes automated LLM-as-a-judge scores.
    </p>
"""

def get_score_class(score):
    try:
        if float(score) >= 4:
            return "score-high"
        return "score-med"
    except:
        return "score-med"

for item in frontend_data:
    html_str += f"""
    <div class="qa-card">
        <div class="qa-question">Q{item['id']}: {item['question']}</div>
        <div class="qa-scores">
            <span class="score-badge {get_score_class(item['groundedness_score'])}">Groundedness: {item['groundedness_score']}/5</span>
            <span class="score-badge {get_score_class(item['relevance_score'])}">Relevance: {item['relevance_score']}/5</span>
        </div>
        <div class="qa-answer"><strong>Generated Answer:</strong><br/><br/>{item['answer']}</div>
        <details>
            <summary class="qa-context-summary">View Retrieved Context</summary>
            <div class="qa-context">{item['context']}</div>
        </details>
    </div>
    """

html_str += "</div>"

# Render the UI
display(HTML(html_str))

"""##Summary: Business value and deployment strategy defined

### Next Steps: Model and Data Enhancements

**Broaden the reference corpus:** Incorporate additional peer-reviewed medical literature and specialty-specific guidelines to expand clinical coverage and reduce dependency on a single source.

**Improve retrieval fidelity**:
Further optimize chunking strategy, embedding selection, and top-k retrieval parameters to ensure critical clinical context is consistently surfaced, particularly for complex or cross-sectional queries.

**Adopt domain-specialized embeddings**:
Evaluate medical-domain embedding models to improve semantic accuracy for nuanced clinical terminology.

**Strengthen evaluation rigor**:
Expand automated and human-in-the-loop evaluation using real-world clinical queries to monitor performance over time and identify degradation or bias.

**Productization and System Readiness**:
evelop a front-end dashboard
Implement a secure, user-facing interface that enables clinicians and reviewers to:

**Submit queries**:
View generated answers alongside cited source excerpts

**Inspect relevance and groundedness scores**:
This capability is essential for transparency, trust, and executive oversight.

**Enable auditability and governance**:
Persist query logs, retrieved references, and model outputs to support compliance, internal review, and regulatory readiness.

**Optimize deployment architecture**:
Assess inference performance, cost, and scalability trade-offs to support broader adoption across clinical environments.

**Strategic and Business Considerations**:
Pilot deployment
Introduce the system to a limited cohort of healthcare professionals to validate usability, workflow impact, and time savings.

**Clinical domain expansion**:
Extend the solution into high-impact specialties (e.g., emergency medicine, critical care) where rapid access to grounded information is especially valuable.

**Clear positioning and risk management**:
Maintain explicit positioning as a clinical decision-support tool, reinforcing that it augments—not replaces—professional medical judgment.

### Expanded Executive Summary

Healthcare organizations increasingly seek to leverage AI to improve efficiency and decision-making; however, the use of unconstrained generative models in clinical settings introduces unacceptable risk. This project directly addresses that concern by implementing a system architecture that prioritizes traceability, evidentiary grounding, and professional rigor. Rather than generating responses solely from a model’s internal knowledge, the system retrieves relevant passages from a trusted medical reference and restricts generation to that retrieved content.

From a technical perspective, the system processes more than 4,000 pages of structured medical content, converts them into semantically indexed representations, and retrieves the most relevant sections for each query. These sections are incorporated into carefully controlled prompts that enforce a professional medical tone and explicit citation behavior. This design significantly reduces hallucination risk and ensures that outputs remain aligned with established clinical guidance.

The system’s value is already evident. Automated evaluations consistently confirm that responses are both relevant to the question posed and grounded in source material. This translates into practical benefits for healthcare professionals, including reduced manual search effort, more standardized diagnostic information, and increased confidence in AI-assisted insights.

Looking ahead, the platform provides a strong foundation for scalable clinical decision support. By expanding reference sources, improving retrieval precision, and introducing a transparent front-end interface, the system can evolve into a production-grade solution aligned with organizational governance requirements. Importantly, the architecture supports a balanced approach to innovation—enabling leadership to capture the benefits of AI while maintaining control over accuracy, risk, and accountability.
"""