# -*- coding: utf-8 -*-
"""visa_approval_pred__bin_cls__ensemble_imb_exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUMjM3G4E6wj23W7_fmAL_4l_O_2blIz

# **Visa Approval Prediction**: Supervised Binary Classification Ensemble
---

## **Value Proposition**

In order to streamline the U.S. visa evaluation process an ensemble model was developed that achieves balanced 70% accuracy for both certified and denied applications, supporting consistent decision-making across 775,000+ annual employer applications processed by OFLC.

---

## **Executive Summary**


### Business Opportunities

* **Opportunity A:** The OFLC processed 775,979 employer applications in FY 2016, a 9% year-over-year increase. Manual review of every case is unsustainable at this scale.

* **Solution A:** A machine learning model that pre-screens applications enables faster processing while maintaining compliance integrity.

* **Opportunity B:** Both false approvals (certifying weak applications) and false denials (rejecting qualified applicants) carry significant operational and legal risk.

* **Solution B:** The model achieves balanced 70% accuracy on both certified and denied classes at the optimized threshold, reducing bias toward either outcome.

* **Opportunity C:** Applicant profiling based on key drivers (education, experience, wage) can support downstream policy and workforce planning.

* **Solution C** (Options): Automated pre-screening layer for OFLC case intake. Decision-support dashboard for adjudicators highlighting high-confidence cases. Analytical reporting on approval trends by region, education, and employer size.


### Outcomes

* **Model Performance**

  * Gradient Boosting (Tuned) achieved ROC-AUC of 0.775 and F1 of 0.819 at the default threshold.

  * At the balanced operating threshold (0.680): 70.3% of certified and 69.7% of denied applications correctly classified.

* **Architecture**

  * Gradient Boosting with class weighting and threshold tuning balances sensitivity to both approval and denial classes.

  * SMOTE oversampling and undersampling were tested but did not outperform class-weighted approaches on validation data.

* **Economic Impact**

  * Automating pre-screening of 775,000+ applications annually reduces manual review workload and accelerates processing timelines, while balanced accuracy minimizes both false approval and false denial risks.

* **Strategy Recommendation**

  * Enterprise: Deploy as a pre-screening layer within existing OFLC workflows, routing high-confidence cases for expedited review.

  * SMB: Use as a decision-support tool for immigration law firms advising employers on application strength.


---

## **Problem Space**


### Overview

* U.S. employers face increasing demand for foreign labor certification, with annual applications growing 9% year-over-year.

* Manual review of each case is time-intensive and inconsistent at scale.

* Both false approvals and false denials carry operational and compliance risks.


### Data Description

* 25,480 visa application records with 12 features:
  * `case_id`: Application identifier
  * `continent`: Employee's continent of origin
  * `education_of_employee`: Education level (High School, Bachelor's, Master's, Doctorate)
  * `has_job_experience`: Prior job experience (Y/N)
  * `requires_job_training`: Job training required (Y/N)
  * `no_of_employees`: Employer company size
  * `yr_of_estab`: Year employer was established
  * `region_of_employment`: U.S. region of intended employment
  * `prevailing_wage`: Average wage for the occupation in the area
  * `unit_of_wage`: Wage unit (Hourly, Weekly, Monthly, Yearly)
  * `full_time_position`: Full-time or part-time (Y/N)
  * `case_status`: Target — Certified (1) or Denied (0)

* Class distribution: ~67% Certified, ~33% Denied.

### Process

* Data cleaning standardized categorical values, corrected inconsistencies, and annualized wages for comparability.
* Multiple classifiers tested: Logistic Regression, Decision Tree, Random Forest, Bagging, AdaBoost, Gradient Boosting, XGBoost.
* Class imbalance addressed via SMOTE, undersampling, and class weighting.
* Hyperparameter tuning via RandomizedSearchCV, followed by threshold optimization for balanced performance.


### Results
>| Model | Accuracy | F1 (Certified) | ROC-AUC | Specificity (Denied) |
>|---|---|---|---|---|
>| Model 1: Decision Tree (Weighted) | 0.667 | 0.754 | 0.617 | 0.469 |
>| Model 2: Logistic Regression (Weighted) | 0.705 | 0.767 | 0.767 | 0.663 |
>| Model 3: Bagging (DT Base) | 0.724 | 0.803 | 0.750 | 0.485 |
>| Model 4: Random Forest (Weighted) | 0.732 | 0.810 | 0.754 | 0.481 |
>| Model 5: AdaBoost | 0.728 | 0.812 | 0.765 | 0.424 |
>| Model 6: XGBoost | 0.738 | 0.815 | 0.764 | 0.486 |
>| **Model 7: Gradient Boosting (Tuned) ✅** | **0.743** | **0.819** | **0.775** | **0.487** |


### Next Steps
* To improve balanced classification performance:
  * Explore advanced feature engineering (interaction terms, wage bins) to better capture certification drivers.
  * Test stacking ensembles combining Gradient Boosting with Logistic Regression for improved specificity.
  * Implement deployment pilot with OFLC adjudicators to validate real-world workflow integration and measure processing time savings.

## **Code Execution**

### **Runtime Configuration**

> **Hardware Accelerator:** **CPU** and **Standard RAM**
>
> Please ensure the Colab runtime is set to this configuration before executing any code cells to avoid memory errors or protracted training times.

### **Library Installation**

**Summary:** Required libraries for modeling, visualization, and evaluation were checked and installed only if missing.

**Observations:** If any required package is newly installed, the notebook will display a restart message and stop so the runtime can be restarted cleanly before continuing.
"""

# ------------------------------
# LIBRARY INSTALLATION
# ------------------------------
# Checks for required Python libraries and installs only missing packages.

import importlib.util  # for checking whether required libraries are already available
import subprocess  # for installing any missing libraries
import sys  # for running pip in the current Python environment
from IPython.display import display, HTML  # for rendering the restart message as notebook output

required_packages = {
    "numpy": "numpy",
    "pandas": "pandas",
    "sklearn": "scikit-learn",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "xgboost": "xgboost",
    "imblearn": "imbalanced-learn",
}

missing_packages = [
    package_name
    for module_name, package_name in required_packages.items()
    if importlib.util.find_spec(module_name) is None
]

if missing_packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing_packages])

    display(HTML("""
    <div style="
        border: 4px solid #d93025;
        background: #fce8e6;
        color: #202124;
        padding: 24px;
        border-radius: 12px;
        font-family: Arial, sans-serif;
        margin: 16px 0;
    ">
        <div style="font-size: 30px; font-weight: 800; color: #b31412; margin-bottom: 12px;">
            Runtime Restart Required
        </div>
        <div style="font-size: 22px; line-height: 1.5; font-weight: 600;">
            This notebook installed missing packages.
            <br><br>
            Please go to <b>Runtime → Restart session</b>
            <br>
            Then run the notebook again from the top.
        </div>
        <div style="font-size: 16px; line-height: 1.6; margin-top: 16px; color: #444;">
            Note: Some reported metrics and charts may differ slightly when the notebook is rerun because parts of the workflow involve randomized data splits, model training variation, and threshold-selection behavior.
        </div>
    </div>
    """))
    raise SystemExit("Restart required before continuing.")
else:
    print("Required libraries are already available. No restart is needed.")

"""### **Imports and Configuration**

**Summary:** Core libraries for data handling, preprocessing, modeling, visualization, and evaluation were imported and configured.

**Observations:** The notebook environment is now ready for data loading, analysis, and model execution.
"""

# ------------------------------
# IMPORTS AND CONFIGURATION
# ------------------------------
# Imports all libraries and configures warnings, random state, and plot theme.

import warnings  # for suppressing non-critical warnings during execution
warnings.filterwarnings("ignore")

import numpy as np  # for numerical operations, random-state control, and array handling
import pandas as pd  # for tabular data loading, cleaning, and analysis
import matplotlib.pyplot as plt  # for charts and model-performance visualizations
import seaborn as sns  # for statistical visualizations and plot styling

from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV  # for splitting and tuning
from sklearn.metrics import (  # for model evaluation and classification diagnostics
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix, classification_report
)
from sklearn.compose import ColumnTransformer  # for column-specific preprocessing pipelines
from sklearn.preprocessing import OneHotEncoder, StandardScaler  # for encoding categoricals and scaling numerics
from sklearn.impute import SimpleImputer  # for filling missing values
from sklearn.pipeline import Pipeline  # for chaining preprocessing and modeling steps
from sklearn.utils.class_weight import compute_class_weight  # for handling class imbalance with weights

from sklearn.linear_model import LogisticRegression  # for weighted linear classification baseline
from sklearn.tree import DecisionTreeClassifier  # for tree-based classification baseline
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier  # for ensemble classifiers

from imblearn.pipeline import Pipeline as ImbPipeline  # for combining preprocessing with resampling
from imblearn.over_sampling import SMOTE  # for synthetic minority oversampling
from imblearn.under_sampling import RandomUnderSampler  # for majority-class undersampling

try:
    from xgboost import XGBClassifier  # for gradient-boosted tree classification
    XGB_OK = True
except Exception:
    XGB_OK = False

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
sns.set_theme(style="whitegrid", context="notebook")

"""### **Data Loading**

**Summary:** The dataset was auto-loaded from the managed GitHub dataset package.

**Observations:** All records loaded successfully; schema matches the expected data dictionary.
"""

# ------------------------------
# DATA LOADING
# ------------------------------
# Downloads the standardized visa dataset automatically and loads it into a DataFrame.

import importlib.util  # for loading the shared data access helper dynamically
import shutil  # for clearing stale notebook-specific cached dataset folders
import sys  # for detecting whether the notebook is running in Colab
import urllib.request  # for downloading the shared helper file from GitHub
from pathlib import Path  # for cross-platform file path handling

HELPER_URL = "https://raw.githubusercontent.com/EvagAIML/000-website-notebooks/main/notebooks/_shared/data_access.py"

SLUG = "visa-approval-pred__bin-cls__ensemble-imb-exp"
EXTRACT_TO = "visa-approval-pred__bin-cls__ensemble-imb-exp__dataset__v1"
ZIP_NAME = "visa-approval-pred__bin-cls__ensemble-imb-exp__dataset__v1.zip"

helper_path = Path("/content/data_access.py") if "google.colab" in sys.modules else Path("./data_access.py")
cache_root = Path("/content/data_cache") if "google.colab" in sys.modules else Path("./data_cache")
session_flag = Path("/content/.visa_cache_refreshed") if "google.colab" in sys.modules else Path(".visa_cache_refreshed")

# Clear stale notebook-specific artifacts once per fresh session
if not session_flag.exists():
    helper_path.unlink(missing_ok=True)
    shutil.rmtree(cache_root / EXTRACT_TO, ignore_errors=True)
    (cache_root / ZIP_NAME).unlink(missing_ok=True)
    session_flag.touch()

urllib.request.urlretrieve(HELPER_URL, helper_path)

spec = importlib.util.spec_from_file_location("data_access", helper_path)
data_access = importlib.util.module_from_spec(spec)
spec.loader.exec_module(data_access)

ensure_dataset = data_access.ensure_dataset

DATA_DIR = ensure_dataset(SLUG)
RAW_DIR = DATA_DIR / "raw"

df = pd.read_csv(RAW_DIR / "visa.csv")

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())
print("\nLast 5 rows:")
display(df.tail())

"""### **Data Understanding**

**Summary:** Data types, missing values, and target class distribution were assessed.

**Observations:** No missing values detected; target split is ~67% Certified / ~33% Denied, confirming moderate class imbalance.

"""

# ------------------------------
# DATA OVERVIEW
# ------------------------------
# Displays data types, missing values, target distribution, and summary statistics.

print("Data Types:\n", df.dtypes)
print("\nMissing Values per Column:")
display(df.isna().sum().sort_values(ascending=False))

print("\nTarget Distribution:")
print(df["case_status"].value_counts())

print("\nNumeric Summary:")
display(df.select_dtypes(include="number").describe().T)

print("\nSample Categorical Values:")
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:\n", df[col].value_counts().head(5))

"""### **Data Cleaning and Feature Preparation**

**Summary:** Categorical labels were standardized, inconsistent entries corrected, and wages annualized.

**Observations:** Dataset cleaned and standardized with consistent formatting across all features.

"""

# ------------------------------
# DATA CLEANING AND FEATURE PREPARATION
# ------------------------------
# Normalizes categoricals, annualizes wages, removes invalid records, and encodes the target.

df_clean = df.copy()

def normalize_yn(x):
    s = str(x).strip().upper()
    if s in {"Y","YES","TRUE","T","1"}: return "YES"
    if s in {"N","NO","FALSE","F","0"}: return "NO"
    return s

for col in ["has_job_experience", "requires_job_training", "full_time_position"]:
    df_clean[col] = df_clean[col].map(normalize_yn)

for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].astype(str).str.strip().str.upper()

if "no_of_employees" in df_clean.columns:
    emp = pd.to_numeric(df_clean["no_of_employees"], errors="coerce")
    neg = emp < 0
    if neg.sum() > 0:
        df_clean.loc[neg, "no_of_employees"] = emp.median()
        print(f"Negative values corrected in 'no_of_employees': {neg.sum()}")

if {"prevailing_wage", "unit_of_wage"}.issubset(df_clean.columns):
    factors = {"HOUR":2080, "WEEK":52, "MONTH":12, "YEAR":1}
    df_clean["unit_of_wage"] = df_clean["unit_of_wage"].astype(str).str.upper().str.strip()
    df_clean["prevailing_wage_yearly"] = df_clean.apply(
        lambda r: pd.to_numeric(r["prevailing_wage"], errors="coerce") * factors.get(r["unit_of_wage"], 1), axis=1
    )
    print("Annualized prevailing wages created.")

if "yr_of_estab" in df_clean.columns:
    years = pd.to_numeric(df_clean["yr_of_estab"], errors="coerce")
    valid = years.between(1800, 2025)
    removed = (~valid).sum()
    df_clean = df_clean.loc[valid]
    print(f"Invalid establishment years removed: {removed}")

df_clean["case_status"] = df_clean["case_status"].map({"DENIED":0, "CERTIFIED":1})
df_clean.dropna(subset=["case_status"], inplace=True)
df_clean["case_status"] = df_clean["case_status"].astype(int)

if "case_id" in df_clean.columns:
    df_clean.drop(columns=["case_id"], inplace=True)

print("Final shape after cleaning:", df_clean.shape)
display(df_clean.head())

"""### **Exploratory Data Analysis (Univariate)**

**Summary:** Individual feature distributions and the target class balance were visualized.

**Observations:** Certified cases form the majority; prevailing wage shows right-skewed distribution with significant variance.

"""

# ------------------------------
# EXPLORATORY ANALYSIS (UNIVARIATE)
# ------------------------------
# Boxplot-histogram combos for numerics; countplots for categoricals.

num_cols = df_clean.select_dtypes(include="number").columns.tolist()
cat_cols = df_clean.select_dtypes(exclude="number").columns.tolist()

for c in [x for x in num_cols if x != "case_status"]:
    fig, axs = plt.subplots(2, 1, figsize=(10, 6), gridspec_kw={'height_ratios':[1,2]}, sharex=True)
    sns.boxplot(x=df_clean[c], ax=axs[0])
    sns.histplot(df_clean[c], kde=True, ax=axs[1])
    axs[0].set_title(f"Boxplot — {c}")
    axs[1].set_title(f"Histogram — {c}")
    plt.tight_layout(); plt.show()

for c in [x for x in cat_cols if x.upper() != "CASE_STATUS"]:
    plt.figure(figsize=(10,4))
    order = df_clean[c].value_counts().index
    sns.countplot(data=df_clean, x=c, order=order)
    plt.title(f"Counts — {c}")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout(); plt.show()

"""### **Exploratory Data Analysis (Bivariate)**

**Summary:** Feature relationships with the target variable were analyzed to identify certification drivers.

**Observations:** Education, job experience, and prevailing wage emerge as the strongest predictors of certification outcome.

"""

# ------------------------------
# EXPLORATORY ANALYSIS (BIVARIATE)
# ------------------------------
# Boxplots, density plots, stacked bars, and correlation heatmap vs. the target.

target = "case_status"

for c in [x for x in num_cols if x != target]:
    fig, axs = plt.subplots(1, 2, figsize=(12, 4))
    sns.boxplot(data=df_clean, x=target, y=c, ax=axs[0])
    sns.kdeplot(data=df_clean, x=c, hue=target, common_norm=False, ax=axs[1])
    axs[0].set_title(f"{c} by Case Outcome")
    axs[1].set_title(f"Density of {c} by Case Outcome")
    plt.tight_layout(); plt.show()

def stacked_bar(data, feature):
    ctab = pd.crosstab(data[feature], data[target], normalize="index")*100
    ctab.plot(kind="bar", stacked=True, figsize=(10,4))
    plt.title(f"{feature}: % Certified vs Denied")
    plt.ylabel("Percentage")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

for c in [x for x in cat_cols if x.upper() != "CASE_STATUS"]:
    stacked_bar(df_clean, c)

plt.figure(figsize=(8,6))
sns.heatmap(df_clean.select_dtypes(include="number").corr(), cmap="coolwarm", annot=False)
plt.title("Correlation Map (Numeric Features)")
plt.tight_layout(); plt.show()

"""### **Analytical Insights**

**Summary:** Key certification patterns were quantified across applicant demographics and employer characteristics.

**Observations:** Certification rates are highest among applicants with advanced education, prior job experience, and higher prevailing wages.

"""

# ------------------------------
# ANALYTICAL INSIGHTS
# ------------------------------
# Certification rates by education, continent, experience, region, and wage level.

def cert_rate_by(df, col):
    table = df.groupby(col)[target].mean().rename("cert_rate").to_frame()
    table["count"] = df.groupby(col)[target].size()
    return table.sort_values("cert_rate", ascending=False)

df_clean["wage_bin"] = pd.qcut(df_clean["prevailing_wage_yearly"], q=4, duplicates="drop")
high_cut = df_clean["prevailing_wage_yearly"].quantile(0.75)
df_highpay = df_clean[df_clean["prevailing_wage_yearly"] >= high_cut]

edu_highpay = cert_rate_by(df_highpay, "education_of_employee")
continent_cert = cert_rate_by(df_clean, "continent")
exp_cert = cert_rate_by(df_clean, "has_job_experience")
region_wage = df_clean.groupby("region_of_employment")["prevailing_wage_yearly"].agg(["count","median","mean"]).sort_values("median", ascending=False)
wage_cert = cert_rate_by(df_clean, "wage_bin")
unit_cert = cert_rate_by(df_clean, "unit_of_wage")

print("Education among high-paid roles:")
display(edu_highpay)
print("\nCertification rate by continent:")
display(continent_cert)
print("\nCertification rate by prior experience:")
display(exp_cert)
print("\nPrevailing wage by region:")
display(region_wage)
print("\nCertification by wage quartile:")
display(wage_cert)
print("\nCertification by wage unit:")
display(unit_cert)

"""### **Data Preparation for Modeling**

**Summary:** Dataset split into Train (15,288), Validation (5,096), and Test (5,096) with stratification.

**Observations:** Stratified splits preserve class ratios across all partitions; features encoded and scaled.

"""

# ------------------------------
# DATA PREPARATION FOR MODELING
# ------------------------------
# 60/20/20 stratified split with a ColumnTransformer pipeline (impute + scale + encode).

X = df_clean.drop(columns=[target])
y = df_clean[target].astype(int)

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, stratify=y, random_state=RANDOM_STATE)
X_valid, X_test, y_valid, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=RANDOM_STATE)

num_cols = X_train.select_dtypes(include="number").columns.tolist()
cat_cols = X_train.select_dtypes(exclude="number").columns.tolist()

numeric_tf = Pipeline([("impute", SimpleImputer(strategy="median")), ("scale", StandardScaler())])
categorical_tf = Pipeline([("impute", SimpleImputer(strategy="most_frequent")), ("encode", OneHotEncoder(handle_unknown="ignore"))])

preprocessor = ColumnTransformer([("num", numeric_tf, num_cols), ("cat", categorical_tf, cat_cols)], remainder="drop")
print("Data preprocessed successfully.")

"""### **Metric and Visualization Utilities**

**Summary:** Utility functions for performance metrics (accuracy, precision, recall, F1, ROC-AUC) and confusion matrix visualization were created.

**Observations:** Standardized evaluation framework enables consistent comparison across all model variants.

"""

# ------------------------------
# METRIC AND VISUALIZATION UTILITIES
# ------------------------------
# Reusable evaluate() and plot_cm() functions for all model experiments.

def evaluate(model, X, y):
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:,1] if hasattr(model.named_steps["clf"], "predict_proba") else None
    acc = accuracy_score(y, y_pred)
    prec = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)
    auc = roc_auc_score(y, y_prob) if y_prob is not None else np.nan
    cm = confusion_matrix(y, y_pred)
    tn, fp, fn, tp = cm.ravel()
    spec = tn/(tn+fp)
    return acc, prec, rec, f1, auc, spec, cm

def plot_cm(cm, title="Confusion Matrix"):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Greens",
                xticklabels=["Pred Denied","Pred Certified"],
                yticklabels=["Actual Denied","Actual Certified"])
    plt.title(title)
    plt.tight_layout(); plt.show()

"""### **Baseline Models (Original Train)**

**Summary:** Seven classifiers were trained on the original (unmodified) training set with class weighting.

**Observations:** Gradient Boosting achieved the best baseline with F1=0.820 and ROC-AUC=0.775, but denied specificity was only 48.9%.

"""

# ------------------------------
# BASELINE MODELS ON ORIGINAL TRAIN
# ------------------------------
# Trains seven class-weighted classifiers and validates on the holdout split.

def make_plain(model):
    return Pipeline([("pre", preprocessor), ("clf", model)])

# Compute weights from the train split (robust to class ratio)
classes = np.array([0,1])
weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weights = {0: float(weights[0]), 1: float(weights[1])}
print("Class weights (train-derived):", class_weights)

orig_models = {
    "Logistic (weighted)":   make_plain(LogisticRegression(
        solver="liblinear", class_weight=class_weights, max_iter=3000, random_state=RANDOM_STATE)),
    "Decision Tree (weighted)": make_plain(DecisionTreeClassifier(
        class_weight=class_weights, random_state=RANDOM_STATE)),
    "Random Forest (weighted)": make_plain(RandomForestClassifier(
        n_estimators=400, class_weight=class_weights, n_jobs=-1, random_state=RANDOM_STATE)),
    "Bagging (DT base)":     make_plain(BaggingClassifier(
        n_estimators=300, random_state=RANDOM_STATE)),
    "AdaBoost":              make_plain(AdaBoostClassifier(
        n_estimators=400, random_state=RANDOM_STATE)),
    "Gradient Boosting":     make_plain(GradientBoostingClassifier(
        random_state=RANDOM_STATE)),
}

# Add XGBoost if available
if XGB_OK:
    orig_models["XGBoost"] = make_plain(XGBClassifier(
        random_state=RANDOM_STATE,
        n_estimators=500, learning_rate=0.1, max_depth=4,
        subsample=0.9, colsample_bytree=0.9, eval_metric="logloss",
        tree_method="hist", n_jobs=-1))

rows, fitted_orig = [], {}
for name, pipe in orig_models.items():
    pipe.fit(X_train, y_train)
    acc, prec, rec, f1, auc, spec, cm = evaluate(pipe, X_valid, y_valid)
    rows.append([name, acc, prec, rec, f1, auc, spec])
    fitted_orig[name] = pipe

orig_perf = (pd.DataFrame(rows, columns=["Model","Accuracy","Precision(1)","Recall(1)",
                                        "F1(1)","ROC_AUC","Spec(0)"])
             .sort_values(by=["F1(1)","ROC_AUC"], ascending=False).reset_index(drop=True))

print("=== ORIGINAL TRAIN — Validation Results ===")
display(orig_perf.round(4))

"""### **Models with SMOTE Oversampling**

**Summary:** Models were retrained on SMOTE-oversampled data to improve minority class detection.

**Observations:** SMOTE increased denied specificity to ~56–65% but decreased certified recall, with no net F1 improvement over baseline.

"""

# ------------------------------
# MODEL BUILDING — OVERSAMPLED TRAIN (SMOTE)
# ------------------------------
# Trains models with SMOTE synthetic oversampling inside imblearn pipelines.

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

def make_smote(model):
    return ImbPipeline([
        ("pre", preprocessor),
        ("smote", SMOTE(random_state=RANDOM_STATE)),
        ("clf", model)
    ])

smote_models = {
    "Logistic + SMOTE (weighted)": make_smote(LogisticRegression(
        solver="liblinear", class_weight=class_weights, max_iter=3000, random_state=RANDOM_STATE)),
    "Decision Tree + SMOTE (weighted)": make_smote(DecisionTreeClassifier(
        class_weight=class_weights, random_state=RANDOM_STATE)),
    "Random Forest + SMOTE (weighted)": make_smote(RandomForestClassifier(
        n_estimators=400, class_weight=class_weights, n_jobs=-1, random_state=RANDOM_STATE)),
    "Gradient Boosting + SMOTE": make_smote(GradientBoostingClassifier(random_state=RANDOM_STATE)),
    "AdaBoost + SMOTE": make_smote(AdaBoostClassifier(n_estimators=400, random_state=RANDOM_STATE))
}

rows, fitted_smote = [], {}
for name, pipe in smote_models.items():
    pipe.fit(X_train, y_train)
    acc, prec, rec, f1, auc, spec, cm = evaluate(pipe, X_valid, y_valid)
    rows.append([name, acc, prec, rec, f1, auc, spec])
    fitted_smote[name] = pipe

smote_perf = pd.DataFrame(rows, columns=["Model","Accuracy","Precision(1)","Recall(1)",
                                         "F1(1)","ROC_AUC","Spec(0)"])\
                            .sort_values(by=["F1(1)","Spec(0)"], ascending=False)\
                            .reset_index(drop=True)

print("=== SMOTE TRAIN — Validation Results ===")
display(smote_perf.round(4))

"""### **Models with Undersampling**

**Summary:** Models were retrained on undersampled data to balance class representation.

**Observations:** Undersampling improved denied specificity to ~63–68% but further reduced certified recall, confirming class-weighted baselines are more effective.

"""

# ------------------------------
# MODEL BUILDING — UNDERSAMPLED TRAIN
# ------------------------------
# Trains models with random undersampling inside imblearn pipelines.

from imblearn.under_sampling import RandomUnderSampler

def make_under(model):
    return ImbPipeline([
        ("pre", preprocessor),
        ("under", RandomUnderSampler(random_state=RANDOM_STATE)),
        ("clf", model)
    ])

under_models = {
    "Logistic + Under (weighted)": make_under(LogisticRegression(
        solver="liblinear", class_weight=class_weights, max_iter=3000, random_state=RANDOM_STATE)),
    "Decision Tree + Under (weighted)": make_under(DecisionTreeClassifier(
        class_weight=class_weights, random_state=RANDOM_STATE)),
    "Random Forest + Under (weighted)": make_under(RandomForestClassifier(
        n_estimators=400, class_weight=class_weights, n_jobs=-1, random_state=RANDOM_STATE)),
    "Gradient Boosting + Under": make_under(GradientBoostingClassifier(random_state=RANDOM_STATE)),
    "AdaBoost + Under": make_under(AdaBoostClassifier(n_estimators=400, random_state=RANDOM_STATE))
}

rows, fitted_under = [], {}
for name, pipe in under_models.items():
    pipe.fit(X_train, y_train)
    acc, prec, rec, f1, auc, spec, cm = evaluate(pipe, X_valid, y_valid)
    rows.append([name, acc, prec, rec, f1, auc, spec])
    fitted_under[name] = pipe

under_perf = pd.DataFrame(rows, columns=["Model","Accuracy","Precision(1)","Recall(1)",
                                         "F1(1)","ROC_AUC","Spec(0)"])\
                            .sort_values(by=["F1(1)","Spec(0)"], ascending=False)\
                            .reset_index(drop=True)

print("=== UNDERSAMPLED TRAIN — Validation Results ===")
display(under_perf.round(4))

"""### **Top Candidate Selection**

**Summary:** Best-performing models across all resampling strategies were ranked for hyperparameter tuning.

**Observations:** Gradient Boosting, Random Forest, and XGBoost from the original weighted baseline consistently dominate across metrics.

"""

# ------------------------------
# TOP CANDIDATE SELECTION
# ------------------------------
# Picks the top models by F1 and specificity across all resampling strategies.

def pick_top(df, k=3):
    return df.sort_values(by=["F1(1)","Spec(0)"], ascending=False).head(k)["Model"].tolist()

candidates = list(dict.fromkeys(
    pick_top(orig_perf, 3) + pick_top(smote_perf, 3) + pick_top(under_perf, 3)
))

print("=== Top Candidates for Tuning ===")
for c in candidates:
    print(" -", c)

"""### **Hyperparameter Tuning**

**Summary:** Gradient Boosting was optimized via RandomizedSearchCV with cross-validation.

**Observations:** Tuned Gradient Boosting achieved F1=0.819 and ROC-AUC=0.775, confirming marginal but consistent improvement over baseline.

"""

# ------------------------------
# HYPERPARAMETER TUNING
# ------------------------------
# RandomizedSearchCV with 5-fold stratified CV on top candidates, optimizing F1.
# sklearn: RandomizedSearchCV, StratifiedKFold. scipy.stats: loguniform, randint.

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from scipy.stats import loguniform, randint

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

def build_model_by_name(name):
    if "Gradient Boosting" in name:
        base = GradientBoostingClassifier(random_state=RANDOM_STATE)
        pipe = make_plain(base)
        params = {
            "clf__n_estimators": [200, 300, 500],
            "clf__learning_rate": [0.05, 0.1, 0.2],
            "clf__max_depth": [2, 3, 4],
            "clf__subsample": [0.8, 1.0]
        }
        return pipe, params

    if "Random Forest" in name:
        base = RandomForestClassifier(
            n_estimators=400, class_weight=class_weights, n_jobs=-1, random_state=RANDOM_STATE)
        pipe = make_plain(base)
        params = {
            "clf__max_depth": [None, 10, 20],
            "clf__min_samples_split": [2, 5, 10],
            "clf__min_samples_leaf": [1, 2, 4],
            "clf__max_features": ["sqrt", "log2"]
        }
        return pipe, params

    if "Logistic" in name:
        base = LogisticRegression(
            solver="liblinear", class_weight=class_weights, max_iter=4000, random_state=RANDOM_STATE)
        pipe = make_plain(base)
        params = {"clf__C": loguniform(1e-3, 1e2), "clf__penalty": ["l1", "l2"]}
        return pipe, params

    return None

tuned_models, results = {}, []
for name in candidates[:3]:
    built = build_model_by_name(name)
    if built is None:
        continue
    pipe, grid = built
    tuner = RandomizedSearchCV(
        estimator=pipe,
        param_distributions=grid,
        n_iter=20,
        scoring="f1",
        cv=cv,
        n_jobs=-1,
        random_state=RANDOM_STATE,
        refit=True,
        verbose=0
    )
    tuner.fit(X_train, y_train)
    tuned_models[name] = tuner.best_estimator_

    acc, prec, rec, f1, auc, spec, cm = evaluate(tuner.best_estimator_, X_valid, y_valid)
    results.append([name, tuner.best_params_, acc, prec, rec, f1, auc, spec])

tuned_df = pd.DataFrame(results, columns=[
    "Model","Best Params","Accuracy","Precision(1)","Recall(1)","F1(1)","ROC_AUC","Spec(0)"
]).sort_values(by=["F1(1)","Spec(0)"], ascending=False).reset_index(drop=True)

print("=== Tuned Models — Validation ===")
display(tuned_df)

best_name = tuned_df.iloc[0]["Model"]
best_model = tuned_models[best_name]
print("Selected tuned model:", best_name)

"""### **Threshold Optimization**

**Summary:** Multiple probability thresholds were evaluated to balance certified recall and denied specificity.

**Observations:** Best-F1 threshold (0.430) maximizes certified detection; even-balance threshold (0.680) achieves ~70% accuracy on both classes.

"""

# ------------------------------
# THRESHOLD OPTIMIZATION
# ------------------------------
# Sweeps thresholds 0.20–0.80 to balance F1 and denied-class specificity.

def proba_positive(pipe, X):
    clf = pipe.named_steps["clf"]
    if hasattr(clf, "predict_proba"):
        return pipe.predict_proba(X)[:, 1]
    raise RuntimeError("This model does not support predict_proba().")

val_prob = proba_positive(best_model, X_valid)

thresholds = np.linspace(0.2, 0.8, 121)
records = []
for t in thresholds:
    y_pred = (val_prob >= t).astype(int)
    acc = accuracy_score(y_valid, y_pred)
    prec = precision_score(y_valid, y_pred, zero_division=0)
    rec = recall_score(y_valid, y_pred, zero_division=0)
    f1 = f1_score(y_valid, y_pred, zero_division=0)
    tn, fp, fn, tp = confusion_matrix(y_valid, y_pred, labels=[0,1]).ravel()
    spec = tn / (tn + fp) if (tn + fp) else 0
    score = 0.6*f1 + 0.4*spec
    records.append([t, acc, prec, rec, f1, spec, score])

thresh_df = pd.DataFrame(records, columns=["Threshold","Accuracy","Precision(1)","Recall(1)",
                                           "F1(1)","Spec(0)","Score"])\
                        .sort_values(by="Score", ascending=False).reset_index(drop=True)

best_thr = float(thresh_df.iloc[0]["Threshold"])
print("Best operating threshold:", round(best_thr, 3))
display(thresh_df.head(10))

"""### **Validation Threshold Sweep**

**Summary:** Confusion matrices were generated at default (0.50), best-F1 (0.43), and balanced (0.68) thresholds.

**Observations:** At balanced threshold (0.680): certified correctly predicted 70.3%, denied correctly predicted 69.7% — the only operating point achieving near-equal performance on both classes.

"""

# ------------------------------
# VALIDATION THRESHOLD SWEEP — CONFUSION METRICS
# ------------------------------
# Detailed threshold analysis with best-F1, default, and balanced operating points.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix
)

# In case not already defined earlier
def proba_positive(est, X):
    clf = est.named_steps["clf"]
    if hasattr(clf, "predict_proba"):
        return est.predict_proba(X)[:, 1]
    raise RuntimeError("Estimator lacks predict_proba for threshold tuning.")

def eval_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, pos_label=1, zero_division=0)
    rec  = recall_score(y_true, y_pred, pos_label=1, zero_division=0)   # Certified recall
    f1c  = f1_score(y_true, y_pred, pos_label=1, zero_division=0)
    cm   = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    spec = tn/(tn+fp) if (tn+fp) else 0.0                               # Denied specificity
    cert_ok = tp/(tp+fn) if (tp+fn) else 0.0
    den_ok  = tn/(tn+fp) if (tn+fp) else 0.0
    return {
        "threshold": thr, "accuracy": acc, "precision(1)": prec, "recall(1)": rec,
        "f1(1)": f1c, "spec(0)": spec, "cert_ok%": cert_ok, "denied_ok%": den_ok,
        "tn": tn, "fp": fp, "fn": fn, "tp": tp, "cm": cm
    }

def summarize_thresholds(y_true, y_prob, thr_list, title_prefix="Validation", show_heatmaps=False):
    rows = []
    for t in thr_list:
        rows.append(eval_threshold(y_true, y_prob, t))
    df = pd.DataFrame(rows).drop(columns=["cm"])
    df_sorted = df.sort_values(by=["f1(1)", "spec(0)"], ascending=False).reset_index(drop=True)
    display(df_sorted.round(4))

    if show_heatmaps:
        for r in rows:
            cm = r["cm"]
            cm_df = pd.DataFrame(cm,
                                 index=["Actual DENIED (0)", "Actual CERTIFIED (1)"],
                                 columns=["Pred DENIED (0)", "Pred CERTIFIED (1)"])
            plt.figure(figsize=(5.2,4.2))
            sns.heatmap(cm_df, annot=True, fmt="d", cmap="Purples", cbar=True, linewidths=.5)
            plt.title(f"{title_prefix} — Confusion Matrix @ Thr {r['threshold']:.3f}")
            plt.tight_layout(); plt.show()
    return df_sorted

# ---- Run on VALIDATION ----
val_prob = proba_positive(best_model, X_valid)

# Fine sweep to find best-F1 and best "even" (harmonic mean of recall & specificity)
grid = np.linspace(0.20, 0.80, 121)
scan = [eval_threshold(y_valid, val_prob, t) for t in grid]
scan_df = pd.DataFrame(scan).drop(columns=["cm"])
scan_df["even_hmean"] = (2*scan_df["recall(1)"]*scan_df["spec(0)"]) / (
    (scan_df["recall(1)"] + scan_df["spec(0)"]).replace(0, np.nan)
)

VAL_best_f1_threshold   = float(scan_df.loc[scan_df["f1(1)"].idxmax(), "threshold"])
VAL_even_threshold      = float(scan_df.loc[scan_df["even_hmean"].idxmax(), "threshold"])
VAL_default_threshold   = 0.50

print(f"Validation best-F1 threshold   : {VAL_best_f1_threshold:.3f}")
print(f"Validation even-balance thr    : {VAL_even_threshold:.3f}")
print(f"Validation default threshold   : {VAL_default_threshold:.3f}")

# Curated set of thresholds to inspect on VALIDATION
val_thresholds_to_view = sorted({
    VAL_default_threshold,
    round(VAL_best_f1_threshold, 3),
    round(VAL_even_threshold, 3),
    0.60, 0.65, 0.68, 0.70
})

print("\n=== Validation — Metrics at Selected Thresholds ===")
val_table = summarize_thresholds(y_valid, val_prob, val_thresholds_to_view,
                                 title_prefix="Validation", show_heatmaps=False)

"""### **Test Set Threshold Evaluation**

**Summary:** The three threshold operating points were validated on the held-out test set.

**Observations:** Test performance mirrors validation — balanced threshold maintains 70.3% certified / 69.7% denied with ROC-AUC of 0.775.

"""

# ------------------------------
# THRESHOLD SWEEP WITH KEY OPERATING POINTS
# ------------------------------
# Evaluates four threshold strategies on test: default, best-F1, balanced counts, and parity.

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
)

# --- Choose dataset to inspect ---
DATASET = "test"   # "valid" or "test"
if DATASET == "valid":
    X_eval, y_eval = X_valid, y_valid
else:
    X_eval, y_eval = X_test, y_test

# --- Probabilities from the selected model ---
if not hasattr(best_model.named_steps["clf"], "predict_proba"):
    raise RuntimeError("The selected model does not support predict_proba; threshold tuning requires probabilities.")

y_prob = best_model.predict_proba(X_eval)[:, 1]  # P(CERTIFIED)
y_true = y_eval.values if hasattr(y_eval, "values") else y_eval

# --- Helpers ---
def eval_at_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    total = tn + fp + fn + tp

    # Core metrics
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, pos_label=1, zero_division=0)
    rec1 = recall_score(y_true, y_pred, pos_label=1, zero_division=0)        # Certified recall (TPR for class 1)
    f1c  = f1_score(y_true, y_pred, pos_label=1, zero_division=0)
    spec0 = tn / (tn + fp) if (tn + fp) else 0.0                              # Denied specificity (TNR for class 0)

    # Predicted counts & shares
    pred_1 = (y_pred == 1).sum()
    pred_0 = (y_pred == 0).sum()
    share_1 = pred_1 / total
    share_0 = pred_0 / total

    # Class-wise correctness
    tot_denied = tn + fp
    tot_cert   = tp + fn
    denied_correct_pct   = (tn / tot_denied) * 100 if tot_denied else 0.0
    denied_incorrect_pct = (fp / tot_denied) * 100 if tot_denied else 0.0
    cert_correct_pct     = (tp / tot_cert) * 100 if tot_cert else 0.0
    cert_incorrect_pct   = (fn / tot_cert) * 100 if tot_cert else 0.0

    return {
        "thr": thr,
        "acc": acc,
        "prec1": prec,
        "rec1": rec1,
        "spec0": spec0,
        "f1c": f1c,
        "pred_0": int(pred_0), "pred_1": int(pred_1),
        "share_0": share_0, "share_1": share_1,
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),
        "denied_correct_pct": denied_correct_pct,
        "denied_incorrect_pct": denied_incorrect_pct,
        "cert_correct_pct": cert_correct_pct,
        "cert_incorrect_pct": cert_incorrect_pct,
        "cm": cm
    }

# --- Sweep thresholds ---
grid = np.linspace(0.20, 0.80, 121)
rows = [eval_at_threshold(y_true, y_prob, t) for t in grid]
df = pd.DataFrame(rows)

# --- Pick operating points ---
# 1) Default 0.50
pt_default = df.iloc[(df['thr']-0.50).abs().argmin()]

# 2) Best F1 (Certified) — strongest single-score balance for the positive class
pt_best_f1 = df.iloc[df['f1c'].values.argmax()]

# 3) Balanced predicted counts — roughly equal number of predicted 0 and 1
pt_balanced_counts = df.iloc[(df['pred_0'] - df['pred_1']).abs().argmin()]

# 4) Parity of correctness — Certified recall ≈ Denied specificity
pt_parity = df.iloc[(df['rec1'] - df['spec0']).abs().argmin()]

# --- Collate for display ---
def short_row(pt, label):
    return {
        "Point": label,
        "Threshold": round(float(pt['thr']), 3),
        "Accuracy": round(float(pt['acc']), 4),
        "Precision(1)": round(float(pt['prec1']), 4),
        "Recall(1) (Certified)": round(float(pt['rec1']), 4),
        "Specificity(0) (Denied)": round(float(pt['spec0']), 4),
        "F1(1)": round(float(pt['f1c']), 4),
        "Pred Certified (count)": int(pt['pred_1']),
        "Pred Denied (count)": int(pt['pred_0']),
        "Certified correct %": f"{pt['cert_correct_pct']:.2f}%",
        "Denied correct %": f"{pt['denied_correct_pct']:.2f}%"
    }

summary = pd.DataFrame([
    short_row(pt_default, "Default (0.50)"),
    short_row(pt_best_f1, "Best F1 (Certified)"),
    short_row(pt_balanced_counts, "Balanced Predicted Counts"),
    short_row(pt_parity, "Parity of Correctness (Recall≈Specificity)")
])

print(f"=== Threshold Summary on {DATASET.upper()} ===")
display(summary)

# --- Pretty print confusion matrices & correctness breakdown ---
def print_block(pt, label):
    cm = pt['cm']
    tn, fp, fn, tp = pt['tn'], pt['fp'], pt['fn'], pt['tp']
    print(f"\n--- {label} @ threshold={pt['thr']:.3f} ---")
    print(pd.DataFrame(cm,
                       index=["Actual DENIED (0)", "Actual CERTIFIED (1)"],
                       columns=["Pred DENIED (0)", "Pred CERTIFIED (1)"]))
    print(f"\nCounts:")
    print(f"  Predicted CERTIFIED (1): {pt['pred_1']}")
    print(f"  Predicted DENIED (0)   : {pt['pred_0']}")

    print(f"\nCorrectness (% of each actual class):")
    print(f"  Certified correctly predicted: {pt['cert_correct_pct']:.2f}%   (Incorrect: {pt['cert_incorrect_pct']:.2f}%)")
    print(f"  Denied correctly predicted   : {pt['denied_correct_pct']:.2f}%   (Incorrect: {pt['denied_incorrect_pct']:.2f}%)")

    print(f"\nMetrics:")
    print(f"  Accuracy: {pt['acc']:.4f} | Precision(1): {pt['prec1']:.4f} | Recall(1): {pt['rec1']:.4f} | Specificity(0): {pt['spec0']:.4f} | F1(1): {pt['f1c']:.4f}")

print_block(pt_default, "Default (0.50)")
print_block(pt_best_f1, "Best F1 (Certified)")
print_block(pt_balanced_counts, "Balanced Predicted Counts")
print_block(pt_parity, "Parity of Correctness (Recall≈Specificity)")

"""### **Business Alignment**

**Summary:** Model outcomes were mapped against the original OFLC business objectives and compliance requirements.

**Observations:** The model supports fair and efficient pre-screening, correctly classifying ~7 in 10 applications for both outcomes.

"""

# ------------------------------
# BUSINESS ALIGNMENT — OUTCOMES VS. PROBLEM STATEMENT
# ------------------------------
# Translates test-set performance into business narrative with feature importance analysis.

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
)

# -------- Helpers --------
def proba_positive(est, X):
    """P(CERTIFIED=1)."""
    clf = est.named_steps["clf"]
    if hasattr(clf, "predict_proba"):
        return est.predict_proba(X)[:, 1]
    raise RuntimeError("Selected model does not provide predict_proba; required for threshold analysis.")

def evaluate_at_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, pos_label=1, zero_division=0)
    rec1 = recall_score(y_true, y_pred, pos_label=1, zero_division=0)      # Certified recall
    f1c  = f1_score(y_true, y_pred, pos_label=1, zero_division=0)
    spec0 = tn / (tn + fp) if (tn + fp) else 0.0                            # Denied specificity
    auc  = roc_auc_score(y_true, y_prob)

    total_denied = tn + fp
    total_cert   = tp + fn
    out = {
        "Threshold": thr,
        "Accuracy": acc,
        "Precision(1)": prec,
        "Recall(1)_Certified": rec1,
        "Specificity(0)_Denied": spec0,
        "F1(1)": f1c,
        "ROC_AUC": auc,
        "TP": int(tp), "FP": int(fp), "TN": int(tn), "FN": int(fn),
        "Total_Denied": int(total_denied), "Total_Certified": int(total_cert),
        "Cert_Correct_%": (tp / total_cert * 100) if total_cert else 0.0,
        "Denied_Correct_%": (tn / total_denied * 100) if total_denied else 0.0
    }
    return out, cm

def best_f1_threshold_from_valid(model, X_valid, y_valid):
    """Pick threshold that maximizes F1 on VALID; fallback to 0.50 if anything goes wrong."""
    try:
        vprob = proba_positive(model, X_valid)
        grid = np.linspace(0.20, 0.80, 121)
        best_t, best_f1 = 0.50, -1
        for t in grid:
            ypv = (vprob >= t).astype(int)
            f1c = f1_score(y_valid, ypv, pos_label=1, zero_division=0)
            if f1c > best_f1:
                best_f1, best_t = f1c, t
        return float(best_t)
    except Exception:
        return 0.50

def even_threshold_from_valid(model, X_valid, y_valid):
    """Pick threshold that balances Certified recall and Denied specificity on VALID."""
    try:
        vprob = proba_positive(model, X_valid)
        grid = np.linspace(0.20, 0.80, 121)
        best_t, best_hm = 0.50, -1
        for t in grid:
            ypv = (vprob >= t).astype(int)
            cm = confusion_matrix(y_valid, ypv, labels=[0,1])
            tn, fp, fn, tp = cm.ravel()
            rec1 = tp / (tp + fn) if (tp + fn) else 0.0
            spec0 = tn / (tn + fp) if (tn + fp) else 0.0
            hm = (2 * rec1 * spec0) / (rec1 + spec0) if (rec1 + spec0) else 0.0
            if hm > best_hm:
                best_hm, best_t = hm, t
        return float(best_t)
    except Exception:
        return 0.50

# -------- Determine thresholds (use existing ones if defined earlier) --------
try:
    THR_BEST_F1 = VAL_best_f1_threshold  # from earlier cell if present
except NameError:
    THR_BEST_F1 = best_f1_threshold_from_valid(best_model, X_valid, y_valid)

try:
    THR_EVEN = EVEN_thr  # from earlier cell if present
except NameError:
    THR_EVEN = even_threshold_from_valid(best_model, X_valid, y_valid)

THR_DEFAULT = 0.50

# -------- Evaluate on TEST (business acceptance requires held-out test) --------
test_prob = proba_positive(best_model, X_test)

res_default, cm_default = evaluate_at_threshold(y_test, test_prob, THR_DEFAULT)
res_bestf1, cm_bestf1   = evaluate_at_threshold(y_test, test_prob, THR_BEST_F1)
res_even, cm_even       = evaluate_at_threshold(y_test, test_prob, THR_EVEN)

summary = pd.DataFrame([
    {"Point": "Default (0.50)", **{k: v for k, v in res_default.items() if k not in ["TP","FP","TN","FN"]}},
    {"Point": "Best-F1 (Valid-chosen)", **{k: v for k, v in res_bestf1.items() if k not in ["TP","FP","TN","FN"]}},
    {"Point": "Even Recall/Specificity", **{k: v for k, v in res_even.items() if k not in ["TP","FP","TN","FN"]}},
]).round(4)

print("=== Business Alignment Summary (TEST) ===")
display(summary)

def print_confusion_block(name, res, cm):
    print(f"\n--- {name} @ threshold={res['Threshold']:.3f} ---")
    print(pd.DataFrame(cm,
                       index=["Actual DENIED (0)", "Actual CERTIFIED (1)"],
                       columns=["Pred DENIED (0)", "Pred CERTIFIED (1)"]))
    print(f"Certified correctly predicted: {res['Cert_Correct_%']:.2f}% "
          f"({res['TP']} / {res['Total_Certified']})")
    print(f"Denied    correctly predicted: {res['Denied_Correct_%']:.2f}% "
          f"({res['TN']} / {res['Total_Denied']})")
    print(f"Accuracy={res['Accuracy']:.4f} | Precision(1)={res['Precision(1)']:.4f} | "
          f"Recall(1)={res['Recall(1)_Certified']:.4f} | Specificity(0)={res['Specificity(0)_Denied']:.4f} | "
          f"F1(1)={res['F1(1)']:.4f} | ROC_AUC={res['ROC_AUC']:.4f}")

print_confusion_block("Default (0.50)", res_default, cm_default)
print_confusion_block("Best-F1 (Valid-chosen)", res_bestf1, cm_bestf1)
print_confusion_block("Even Recall/Specificity", res_even, cm_even)

# -------- Drivers of recommendation (top features) --------
# Try to extract model-native importances; fallback to permutation on VALID if needed.
def get_feature_names_from_ct(ct):
    """Get transformed feature names from ColumnTransformer."""
    feat_names = []
    for name, trans, cols in ct.transformers_:
        if name == 'remainder' and trans == 'drop':
            continue
        if hasattr(trans, 'get_feature_names_out'):
            # Pipelines: last step may be OHE
            try:
                fn = trans.get_feature_names_out(cols)
            except:
                fn = cols
        else:
            fn = cols
        feat_names.extend(list(fn))
    return np.array(feat_names, dtype=object)

X_names = get_feature_names_from_ct(best_model.named_steps["pre"])

importances = None
clf = best_model.named_steps["clf"]
if hasattr(clf, "feature_importances_"):
    importances = clf.feature_importances_
elif hasattr(clf, "coef_"):
    # Use absolute coefficients (multi-dim safety)
    coef = np.ravel(clf.coef_)
    importances = np.abs(coef)

top_feat_df = None
if importances is not None and len(importances) == len(X_names):
    idx = np.argsort(importances)[::-1][:15]
    top_feat_df = pd.DataFrame({
        "Feature": X_names[idx],
        "Importance": importances[idx]
    })
    print("\nTop drivers (model-native importance/coefficient):")
    display(top_feat_df)
else:
    # Lightweight permutation importance on VALID to avoid leakage
    try:
        from sklearn.inspection import permutation_importance
        val_imp = permutation_importance(best_model, X_valid, y_valid, n_repeats=5, random_state=42, scoring="f1")
        idx = np.argsort(val_imp.importances_mean)[::-1][:15]
        top_feat_df = pd.DataFrame({
            "Feature": X_names[idx],
            "Importance": val_imp.importances_mean[idx]
        })
        print("\nTop drivers (permutation importance on VALID):")
        display(top_feat_df)
    except Exception as e:
        print("\nSkipping feature importance (not supported for this model).", e)

# -------- Executive-readable mapping to the objective --------
def pct(x):
    return f"{100*x:.1f}%"

# Pick the most “balanced” operating point for narrative (Even or Best-F1 depending on context)
narr = res_even if abs(res_even["Recall(1)_Certified"] - res_even["Specificity(0)_Denied"]) <= \
                  abs(res_bestf1["Recall(1)_Certified"] - res_bestf1["Specificity(0)_Denied"]) else res_bestf1
narr_label = "Even Recall/Specificity" if narr is res_even else "Best-F1"

print("\n=== Business Narrative (TEST) ===")
print(
    f"At the '{narr_label}' operating point (threshold={narr['Threshold']:.3f}), the model correctly identifies "
    f"{narr['Cert_Correct_%']:.1f}% of certified cases and {narr['Denied_Correct_%']:.1f}% of denied cases, "
    f"with overall accuracy {pct(narr['Accuracy'])}, F1 for certified {pct(narr['F1(1)'])}, and ROC-AUC {pct(narr['ROC_AUC'])}."
)
print(
    "This directly supports the objective to facilitate approvals (high true-positive rate on certifications) "
    "while protecting U.S. workers by screening out weak applications (strong true-negative rate on denials)."
)

if top_feat_df is not None:
    top_txt = ", ".join(top_feat_df['Feature'].head(5).tolist())
    print(f"Key decision drivers include: {top_txt}. These features inform which profiles are more likely to be certified or denied.")

print("\nInterpretation for stakeholders:")
print(
    "- For operations: the chosen threshold sets how aggressive the shortlisting is. Moving it higher increases the share of predicted denials (more conservative), "
    "moving it lower increases predicted certifications (more throughput)."
)
print(
    "- For compliance and risk: the Even setting balances catching denials with approving qualified applicants, which is easier to justify in audits."
)

"""### **Expanded Executive Summary**

**TLDR**

Gradient Boosting (Tuned) was selected with the highest ROC-AUC (0.775) and F1 (0.819). At the balanced operating threshold (0.680), it correctly classifies 70.3% of certified and 69.7% of denied applications — the only configuration achieving near-equal performance on both classes, which is critical for regulatory fairness across 775,000+ annual applications.

**Full Summary**

**Objective:** The U.S. Office of Foreign Labor Certification processed 775,979 employer applications in FY 2016, a 9% increase year-over-year. Manual review of every case is unsustainable, and the process demands a data-driven solution that balances approval facilitation with worker protection compliance.

**Data and Preparation:** The dataset contains 25,480 visa applications with 12 features spanning employee demographics (education, experience, continent) and employer characteristics (company size, establishment year, region, prevailing wage). After standardization and annualization of wages, the data was split into 60/20/20 stratified partitions.

**Iterative Development:** Seven classifiers were tested across three resampling strategies (original with class weights, SMOTE oversampling, undersampling). Gradient Boosting consistently dominated on F1 and ROC-AUC. SMOTE and undersampling improved denied specificity but at the cost of certified recall, offering no net improvement.

**Threshold Selection:** The default threshold (0.500) favors certified detection (86.5% recall) but misclassifies nearly half of denied applications (50.6% specificity). The balanced threshold (0.680) sacrifices some certified recall to achieve near-equal 70% performance on both classes — the optimal operating point for regulatory fairness.

**Deployment Readiness:** The final model provides a reliable pre-screening tool that correctly identifies about 7 in 10 certifications and denials, enabling faster processing while maintaining compliance integrity. Key decision drivers include education level, job experience, and prevailing wage.

**Next Steps:** To improve balanced classification performance, the next phase should explore advanced feature engineering (interaction terms, wage bins) to better capture certification drivers, test stacking ensembles combining Gradient Boosting with Logistic Regression for improved specificity, and implement a deployment pilot with OFLC adjudicators to validate real-world workflow integration and measure processing time savings.
"""